Repository sofastack/sofa-rpc, pull requests merged in 2018-06, with the labels that each got.

#161 Upgrade version to 5.4.1-SNAPSHOT.
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: upgrade

#163 Full epoll support on linux.
  core/api/src/main/java/com/alipay/sofa/rpc/config/ServerConfig.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/AbstractHttp2ClientTransport.java
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/RestServer.java
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/SofaNettyJaxrsServer.java
Labels: optimization

#169 Upgrade version to v5.3.4-SNAPSHOT.
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: upgrade

#172 Remove duplicate code.
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/message/bolt/BoltSendableResponseCallback.java
Labels: bug

#173 Fix possible NPE.
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/client/AllConnectConnectionHolderTest.java
Labels: optimization

#175 Remove duplicate code.
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/message/bolt/BoltSendableResponseCallback.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/async/AsyncChainTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/async/AsyncHelloService.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/async/AsyncHelloServiceImpl.java
Labels: bug

#176 Fix possible NPE.
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/client/AllConnectConnectionHolderTest.java
Labels: optimization

#181 Upgrade version of bolt and lookout.
  all/pom.xml
  bom/pom.xml
  extension-impl/metrics-lookout/pom.xml
  test/test-integration/pom.xml
Labels: upgrade

#180 Remove dead connection from manager before reconnect.
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/server/http/AbstractHttpServer.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/server/http/HttpServerHandler.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/AbstractHttp2ClientTransport.java
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/RestServer.java
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/SofaNettyJaxrsServer.java
  test/test-common/src/main/java/com/alipay/sofa/rpc/test/TestUtils.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/client/bolt/BoltDirectUrlTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/client/h2c/H2cDirectUrlTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/client/rest/RestDirectUrlTest.java
Labels: bug

#179 add support for http2 prior knownledge mode (#164)
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcOptions.java
  core/common/src/main/resources/com/alipay/sofa/rpc/common/rpc-config-default.json
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/Http2ClientInitializer.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/transport/http/Http2ClearTextHttpUpgradeTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/transport/http/Http2ClearTextPriorKnowledgeTest.java
Labels: optimization

#190 Fix CI build error on JDK 1.6 which cause by TLS upgrade of the server.
  .travis.yml
  tools/ci/.travis.settings.xml
Labels: optimization

#201 Prepare to release 5.4.1.
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: upgrade

#206 Remove UnsupportedOperationException thrown in notifyListeners
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/message/bolt/BoltResponseFuture.java
Labels: optimization

#208 Upgrade version to 5.4.2-SNAPSHOT.
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: upgrade

#207 Fix consumer exception missing when void method from provider is called with exception.
  .travis.yml
  core-impl/proxy/src/main/java/com/alipay/sofa/rpc/proxy/javassist/JavassistProxy.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/exception/BizThrowExceptionTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/exception/TestExceptionService.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/exception/TestExceptionServiceImpl.java
  tools/ci/.travis.settings.xml
Labels: bug
