Repository sofastack/sofa-rpc, pull requests merged in 2018-08, with the labels that each got.

#249 Upgrade version to 5.5.0-SNAPSHOT.
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: upgrade

#251 Optimize json processing.
  core/common/src/main/java/com/alipay/sofa/rpc/common/json/BeanSerializer.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/json/JSONSerializer.java
Labels: optimization

#254 Fix some typo and warning code.
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AllConnectConnectionHolder.java
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/ElasticConnectionHolder.java
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/SingleGroupAddressHolder.java
  core/api/src/main/java/com/alipay/sofa/rpc/listener/ChannelListener.java
  core/api/src/main/java/com/alipay/sofa/rpc/listener/ConsumerStateListener.java
  core/api/src/main/java/com/alipay/sofa/rpc/listener/ProviderInfoListener.java
  core/api/src/main/java/com/alipay/sofa/rpc/module/Module.java
  core/api/src/main/java/com/alipay/sofa/rpc/protocol/Protocol.java
  core/api/src/main/java/com/alipay/sofa/rpc/protocol/ProtocolNegotiator.java
  core/api/src/main/java/com/alipay/sofa/rpc/protocol/TelnetHandler.java
  core/api/src/main/java/com/alipay/sofa/rpc/proxy/Proxy.java
  core/api/src/main/java/com/alipay/sofa/rpc/server/Server.java
Labels: optimization

#255 Change all confreg to registry
  core/api/src/main/java/com/alipay/sofa/rpc/log/LogCodes.java
  core/api/src/main/resources/sofa-rpc/logcodes-common_en.properties
  core/api/src/main/resources/sofa-rpc/logcodes-common_zh_CN.properties
  extension-impl/registry-local/src/main/java/com/alipay/sofa/rpc/registry/local/LocalRegistry.java
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistry.java
Labels: optimization

#257 Fix change confreg to registry missing spell.
  core/api/src/main/resources/sofa-rpc/logcodes-common_zh_CN.properties
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/common/SofaOptions.java
  extension-impl/registry-local/src/main/java/com/alipay/sofa/rpc/registry/local/LocalRegistryHelper.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubboServerTest.java
Labels: optimization

#260 Use ConcurrentMap to replace the declaration of ConcurrentHashMap objects.
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AllConnectConnectionHolder.java
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/lb/ConsistentHashLoadBalancer.java
  core/api/src/main/java/com/alipay/sofa/rpc/client/ConnectionHolder.java
  core/api/src/main/java/com/alipay/sofa/rpc/client/ProviderInfo.java
  core/api/src/main/java/com/alipay/sofa/rpc/client/RouterChain.java
  core/api/src/main/java/com/alipay/sofa/rpc/codec/CompressorFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/codec/SerializerFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcConfigs.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/ProviderConfig.java
  core/api/src/main/java/com/alipay/sofa/rpc/context/RpcRuntimeContext.java
  core/api/src/main/java/com/alipay/sofa/rpc/event/EventBus.java
  core/api/src/main/java/com/alipay/sofa/rpc/ext/ExtensionLoader.java
  core/api/src/main/java/com/alipay/sofa/rpc/ext/ExtensionLoaderFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/filter/FilterChain.java
  core/api/src/main/java/com/alipay/sofa/rpc/module/ModuleFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/protocol/ProtocolFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/registry/RegistryFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/server/ServerFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/transport/ClientTransportFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/transport/NotReusableClientTransportHolder.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/cache/ReflectCache.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/struct/ConcurrentHashSet.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/struct/TwoWayMap.java
  core/common/src/test/java/com/alipay/sofa/rpc/common/utils/CommonUtilsTest.java
  extension-impl/bootstrap-dubbo/src/main/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubboSingleton.java
  extension-impl/codec-protobuf/src/main/java/com/alipay/sofa/rpc/codec/protobuf/ProtobufHelper.java
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/bootstrap/DefaultConsumerBootstrap.java
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/bootstrap/DefaultProviderBootstrap.java
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/config/UserThreadPoolManager.java
  extension-impl/fault-tolerance/src/main/java/com/alipay/sofa/rpc/client/aft/FaultToleranceConfigManager.java
  extension-impl/fault-tolerance/src/main/java/com/alipay/sofa/rpc/client/aft/InvocationStatFactory.java
  extension-impl/fault-tolerance/src/main/java/com/alipay/sofa/rpc/client/aft/impl/ServiceHorizontalMeasureStrategy.java
  extension-impl/fault-tolerance/src/main/java/com/alipay/sofa/rpc/client/aft/impl/ServiceHorizontalRegulationStrategy.java
  extension-impl/metrics-lookout/src/main/java/com/alipay/sofa/rpc/metrics/lookout/RpcLookoutId.java
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperConfigObserver.java
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperOverrideObserver.java
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperProviderObserver.java
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistry.java
  extension-impl/registry-zk/src/test/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistryTest.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/transport/bolt/BoltClientConnectionManager.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/netty/NettyHelper.java
  test/test-integration/src/test/java/com/alipay/sofa/registry/MockTestRegistry.java
Labels: optimization

#265 Add more test case.
  core/common/src/main/java/com/alipay/sofa/rpc/common/json/BeanSerializer.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/utils/CommonUtils.java
  core/common/src/test/java/com/alipay/sofa/rpc/common/json/BeanSerializerTest.java
  core/common/src/test/java/com/alipay/sofa/rpc/common/json/JSONSerializerTest.java
  core/common/src/test/java/com/alipay/sofa/rpc/common/json/TestJsonBean.java
  core/common/src/test/java/com/alipay/sofa/rpc/common/utils/CommonUtilsTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/multi/MultiProtocolServerExpTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/multi/MultiProtocolServerTest.java
Labels: optimization

#266 Upgrade version 5.4.4
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: upgrade

#268 Prepare 5.4.5.
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: upgrade

#277 Remove dead bolt connection when server is unavailable.
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/transport/bolt/BoltClientConnectionManager.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/client/ReconnectTest.java
Labels: bug, optimization

#267 ConsistentHashLoadBalancer supports weight.
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/lb/WeightConsistentHashLoadBalancer.java
  core-impl/client/src/test/java/com/alipay/sofa/rpc/client/lb/WeightConsistentHashLoadBalancerTest.java
Labels: enhancement

#283 Fix comment.
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/RestServer.java
Labels: optimization

#246 Support consul as registry.
  all/pom.xml
  bom/pom.xml
  core/common/src/main/java/com/alipay/sofa/rpc/common/utils/CommonUtils.java
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/registry/utils/RegistryUtils.java
  extension-impl/pom.xml
  extension-impl/registry-consul/pom.xml
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/ConsulRegistry.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/ConsulRegistryHelper.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/common/ConsulConstants.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/common/ConsulURL.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/common/ConsulURLUtils.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/internal/ConsulManager.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/internal/TtlScheduler.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/model/AbstractBuilder.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/model/ConsulEphemeralNode.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/model/ConsulRouterResp.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/model/ConsulService.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/model/ConsulServiceResp.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/model/ConsulSession.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/model/HeartbeatService.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/model/NotifyConsumerListner.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/model/NotifyListener.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/model/ThrallRoleType.java
  extension-impl/registry-consul/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.registry.Registry
  extension-impl/registry-consul/src/test/java/com/alipay/sofa/rpc/registry/consul/ConsulRegistryTest.java
  extension-impl/registry-consul/src/test/resources/log4j.xml
  extension-impl/registry-consul/src/test/resources/sofa-rpc/rpc-config.json
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistry.java
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistryHelper.java
  test/test-integration/pom.xml
Labels: enhancement, extension

#279 optimize extension loader log
  core/api/src/main/java/com/alipay/sofa/rpc/codec/CompressorFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/codec/SerializerFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/ext/ExtensionLoader.java
  core/api/src/test/java/com/alipay/sofa/rpc/codec/CompressorFactoryTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/codec/SerializerFactoryTest.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/server/http/AbstractHttpServerTask.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/server/http/Http2ServerTask.java
Labels: optimization

#288 Prepare release 545
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-mesh/pom.xml
  extension-impl/registry-mesh/src/test/java/com/alipay/sofa/rpc/registry/mesh/suite/MeshRegistryTest.java
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: upgrade
