Repository sofastack/sofa-rpc, pull requests merged in 2018-05, with the labels that each got.

#77 Fix NPE when invoke asynchronously use JDKProxy.
  core-impl/proxy/src/main/java/com/alipay/sofa/rpc/proxy/jdk/JDKInvocationHandler.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/codec/AllTypeServiceTest.java
  test/test-integration/src/test/resources/sofa-rpc/rpc-config.json
Labels: bug

#88 Make the responsibilities of ProviderInfo more clearer.
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
  core-impl/client/src/test/java/com/alipay/sofa/rpc/client/SingleGroupAddressHolderTest.java
  core/api/src/main/java/com/alipay/sofa/rpc/client/ProviderHelper.java
  core/api/src/main/java/com/alipay/sofa/rpc/client/ProviderInfo.java
  core/api/src/test/java/com/alipay/sofa/rpc/client/ProviderGroupTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/client/ProviderHelperTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/client/ProviderInfoTest.java
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/bootstrap/DefaultConsumerBootstrap.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/FaultToleranceSubscriberTest.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/InvocationStatDimensionStatTest.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/InvocationStatDimensionTest.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/MeasureStrategyTest.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/RegulationStrategyTest.java
  extension-impl/registry-local/src/main/java/com/alipay/sofa/rpc/registry/local/LocalRegistryHelper.java
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistryHelper.java
  extension-impl/remoting-bolt/src/test/java/com/alipay/sofa/rpc/transport/bolt/BoltClientTransportTest.java
  test/test-integration/src/test/java/com/alipay/sofa/registry/MockTestRegistry.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/client/AllConnectConnectionHolderTest.java
Labels: enhancement

#95 Remove version from the keywords of service name.
  core/api/src/main/java/com/alipay/sofa/rpc/config/AbstractInterfaceConfig.java
  core/common/src/main/resources/com/alipay/sofa/rpc/common/rpc-config-default.json
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/bootstrap/DefaultClientProxyInvoker.java
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/config/ConfigUniqueNameGenerator.java
  extension-impl/extension-common/src/test/java/com/alipay/sofa/rpc/config/ConfigUniqueNameGeneratorTest.java
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/SofaResourceFactory.java
Labels: enhancement

#92 issue and pr template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: document

#97 modify issue template
  .github/ISSUE_TEMPLATE/Ask_Question.md
  .github/ISSUE_TEMPLATE/Bug_Report.md
Labels: document

#102 Fix get wrong ProviderInfo when use reuses client transport.
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
  core-impl/transport/src/main/java/com/alipay/sofa/rpc/transport/AbstractProxyClientTransport.java
  core/api/src/main/java/com/alipay/sofa/rpc/context/RpcInternalContext.java
  core/api/src/test/java/com/alipay/sofa/rpc/context/RpcInternalContextTest.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/FaultBaseServiceTest.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/FaultBaseTest.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/server/bolt/BoltServerProcessor.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/transport/bolt/BoltClientTransport.java
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/transport/rest/RestClientTransport.java
Labels: bug

#106 Aggregate caches for better cache management.
  core/api/src/main/java/com/alipay/sofa/rpc/context/RpcRuntimeContext.java
  core/api/src/main/java/com/alipay/sofa/rpc/filter/FilterInvoker.java
  core/api/src/main/java/com/alipay/sofa/rpc/message/MessageBuilder.java
  core/api/src/main/java/com/alipay/sofa/rpc/module/ModuleFactory.java
  core/api/src/test/java/com/alipay/sofa/rpc/common/cache/ReflectCacheTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/message/MessageBuilderTest.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/annotation/VisibleForTesting.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/cache/ReflectCache.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/cache/RpcCacheManager.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/utils/ClassTypeUtils.java
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/common/ReflectCache.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/codec/bolt/SofaRpcSerialization.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/server/bolt/BoltServer.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/server/bolt/BoltServerProcessor.java
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/transport/rest/RestClientTransport.java
Labels: enhancement

#113 Add example and test case of bolt+protobuf.
  example/pom.xml
  example/src/test/java/com/alipay/sofa/rpc/protobuf/EchoRequest.java
  example/src/test/java/com/alipay/sofa/rpc/protobuf/EchoRequestOrBuilder.java
  example/src/test/java/com/alipay/sofa/rpc/protobuf/EchoResponse.java
  example/src/test/java/com/alipay/sofa/rpc/protobuf/EchoResponseOrBuilder.java
  example/src/test/java/com/alipay/sofa/rpc/protobuf/Group.java
  example/src/test/java/com/alipay/sofa/rpc/protobuf/ProtoService.java
  example/src/test/java/com/alipay/sofa/rpc/protobuf/ProtoService.proto
  example/src/test/java/com/alipay/sofa/rpc/protobuf/ProtoServiceImpl.java
  example/src/test/java/com/alipay/sofa/rpc/protobuf/ProtoServiceOuterClass.java
  example/src/test/java/com/alipay/sofa/rpc/protobuf/ProtobufServiceClient.java
  example/src/test/java/com/alipay/sofa/rpc/protobuf/ProtobufServiceServer.java
  example/src/test/java/com/alipay/sofa/rpc/protobuf/gen.sh
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/bolt/BoltProtobufTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/bolt/BoltServerTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/bolt/DiscardTimeoutTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/bolt/NotFoundInvokerTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/bolt/ProtobufService.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/bolt/ProtobufServiceImpl.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/bolt/ProtobufServiceServer.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/bolt/RejectedTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/bolt/pb/EchoRequest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/bolt/pb/EchoRequestOrBuilder.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/bolt/pb/EchoResponse.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/bolt/pb/EchoResponseOrBuilder.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/bolt/pb/Group.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/bolt/pb/ProtoServiceModels.java
Labels: optimization

#123 Post ServerEndHandleEvent after server return when using async chain invoke.
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/message/bolt/BoltSendableResponseCallback.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/server/bolt/BoltServerProcessor.java
Labels: bug

#124 Post ServerEndHandleEvent after server return when using async chain invoke.
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/message/bolt/BoltSendableResponseCallback.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/server/bolt/BoltServerProcessor.java
Labels: bug

#126 Adjust the order of events and record elapsed time when async invoke.
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
  core/api/src/main/java/com/alipay/sofa/rpc/client/ClientProxyInvoker.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcConstants.java
  core/api/src/main/java/com/alipay/sofa/rpc/context/RpcInternalContext.java
  core/api/src/test/java/com/alipay/sofa/rpc/context/RpcInternalContextTest.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/message/bolt/AbstractInvokeCallback.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/message/bolt/BoltFutureInvokeCallback.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/message/bolt/BoltInvokerCallback.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/transport/bolt/BoltClientTransport.java
  extension-impl/remoting-bolt/src/test/java/com/alipay/sofa/rpc/message/bolt/AbstractInvokeCallbackTest.java
Labels: bug, optimization

#129 Set default connection pool size of RestClient to 80.
  example/src/test/java/com/alipay/sofa/rpc/rest/start/RestClientMultipleMain.java
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/transport/rest/RestClientTransport.java
Labels: bug

#134 Fix some wrong usage of the logger.
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AllConnectConnectionHolder.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/server/bolt/BoltServerProcessor.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/transport/bolt/BoltClientTransport.java
  extension-impl/remoting-bolt/src/test/resources/log4j.xml
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/server/DiscardTimeoutTest.java
Labels: bug

#131 Integrate with sofa-tracer for support opentracing.
  all/pom.xml
  bom/pom.xml
  extension-impl/extension-common/src/main/resources/sofa-rpc/rpc-config.json
  extension-impl/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/event/RestTracerSubscriber.java
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/module/RestTracerModule.java
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/TraceRequestFilter.java
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/TraceResponseFilter.java
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/RestTracerAdapter.java
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/transport/rest/TraceClientRequestFilter.java
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/transport/rest/TraceClientResponseFilter.java
  extension-impl/tracer-opentracing-resteasy/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.module.Module
  extension-impl/tracer-opentracing/pom.xml
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/event/SofaTracerSubscriber.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/filter/sofatracer/ConsumerTracerFilter.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/filter/sofatracer/ProviderTracerFilter.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/module/SofaTracerModule.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/RpcSofaTracer.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/code/TracerResultCode.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/factory/MemoryReporterImpl.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/factory/ReporterFactory.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/log/digest/RpcClientDigestSpanJsonEncoder.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/log/digest/RpcServerDigestSpanJsonEncoder.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/log/stat/AbstractRpcStatJsonReporter.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/log/stat/RpcClientStatJsonReporter.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/log/stat/RpcServerStatJsonReporter.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/log/tags/RpcSpanTags.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/log/type/RpcTracerLogEnum.java
  extension-impl/tracer-opentracing/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.filter.Filter
  extension-impl/tracer-opentracing/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.module.Module
  extension-impl/tracer-opentracing/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.tracer.Tracer
  extension-impl/tracer-opentracing/src/test/java/com/alipay/sofa/rpc/tracer/sofatracer/RpcSofaTracerTest.java
  extension-impl/tracer-opentracing/src/test/java/com/alipay/sofa/rpc/tracer/sofatracer/base/AbstractTracerBase.java
  extension-impl/tracer-opentracing/src/test/java/com/alipay/sofa/rpc/tracer/sofatracer/log/digest/RpcClientDigestSpanEncoderTest.java
  extension-impl/tracer-opentracing/src/test/java/com/alipay/sofa/rpc/tracer/sofatracer/log/stat/RpcClientStatTest.java
  test/test-integration/pom.xml
  test/test-integration/src/test/java/com/alipay/sofa/lookout/RpcLookoutTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/rest/RestTracerTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/client/FailoverClusterTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/tracer/sofatracer/AbstractTracerBase.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/tracer/sofatracer/TracerService.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/tracer/sofatracer/TracerServiceImpl.java
Labels: extension

#137 Use embedded zookeeper for integration test.
  .travis.yml
  bom/pom.xml
  extension-impl/bootstrap-dubbo/src/main/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubboSingleton.java
  extension-impl/registry-zk/pom.xml
  extension-impl/registry-zk/src/test/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistryTest.java
  extension-impl/registry-zk/src/test/java/com/alipay/sofa/rpc/registry/zk/base/BaseZkTest.java
  pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/base/BaseZkTest.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubooServerTest.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/registry/zk/WarmUpTest.java
Labels: optimization

#145 Remove return type of Serializer#decode.
  core/api/src/main/java/com/alipay/sofa/rpc/codec/Serializer.java
  core/api/src/test/java/com/alipay/sofa/rpc/codec/AbstractSerializerTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/codec/TestSerializer.java
  extension-impl/codec-protobuf/src/main/java/com/alipay/sofa/rpc/codec/protobuf/ProtobufSerializer.java
  extension-impl/codec-protobuf/src/test/java/com/alipay/sofa/rpc/codec/protobuf/ProtobufSerializerTest.java
  extension-impl/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SofaHessianSerializer.java
  extension-impl/codec-sofa-hessian/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.codec.Serializer
  extension-impl/codec-sofa-hessian/src/test/java/com/alipay/sofa/rpc/codec/sofahessian/SofaHessianSerializerTest.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/codec/bolt/SofaRpcSerialization.java
Labels: optimization

#147 Upgrade netty version to 4.1.25.Final.
  all/pom.xml
  bom/pom.xml
Labels: upgrade

#149 Fix the provider config repeated export limit.
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/bootstrap/DefaultProviderBootstrap.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/bootstrap/bolt/BoltConsumerBootstrapTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/bootstrap/bolt/BoltProviderBootstrapTest.java
Labels: bug

#150 Prepare to release v5.3.3.
  README.md
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/registry/zk/WarmUpTest.java
  test/test-integration/pom.xml
  tools/change_version.sh
Labels: document, optimization, upgrade

#151 Fix the provider config repeated export limit.
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/bootstrap/DefaultProviderBootstrap.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubboServerTest.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/registry/zk/WarmUpTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/bootstrap/bolt/BoltConsumerBootstrapTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/bootstrap/bolt/BoltProviderBootstrapTest.java
Labels: bug

#152 Prepare to release v5.4.0.
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  extension-impl/metrics-lookout/pom.xml
  extension-impl/remoting-http/pom.xml
  tools/change_version.sh
Labels: upgrade
