Repository sofastack/sofa-rpc, pull requests merged in 2018-12, with the labels that each got.

#390 update version to 5.4.8
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-mesh/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: upgrade

#392 Optimize imports and authors.
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/SingleGroupAddressHolder.java
  core-impl/client/src/test/java/com/alipay/sofa/rpc/client/lb/ConsistentHashLoadBalancerTest.java
  core-impl/client/src/test/java/com/alipay/sofa/rpc/client/lb/WeightRoundRobinLoadBalancerTest.java
  core/api/src/main/java/com/alipay/sofa/rpc/event/ConsumerSubEvent.java
  core/api/src/main/java/com/alipay/sofa/rpc/event/ProviderPubEvent.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/json/BeanSerializer.java
  extension-impl/bootstrap-dubbo/src/main/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubboProviderBootstrap.java
  extension-impl/bootstrap-dubbo/src/test/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubooServerTest.java
  extension-impl/bootstrap-dubbo/src/test/java/com/alipay/sofa/rpc/bootstrap/dubbo/demo/DemoServiceImpl.java
  extension-impl/extension-common/src/test/java/com/alipay/sofa/rpc/bootstrap/DefaultProviderBootstrapTest.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/FaultBaseServiceTest.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/FaultBaseTest.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/bean/FaultHelloService.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/bean/FaultHelloService2.java
  extension-impl/log-common-tools/src/test/java/com/alipay/sofa/rpc/log/factory/RpcLoggerFactoryTest.java
  extension-impl/metrics-lookout/src/main/java/com/alipay/sofa/rpc/event/LookoutSubscriber.java
  extension-impl/registry-local/src/test/java/com/alipay/sofa/rpc/registry/local/LocalRegistryHelperTest.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/client/MeshApiClient.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/ApplicationInfoRequest.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/ApplicationInfoResult.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/MeshConstants.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/MeshEndpoint.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/ProviderMetaInfo.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/PublishServiceRequest.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/PublishServiceResult.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/SubscribeServiceRequest.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/SubscribeServiceResult.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/UnPublishServiceRequest.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/UnPublishServiceResult.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/UnSubscribeServiceRequest.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/UnSubscribeServiceResult.java
  extension-impl/registry-mesh/src/test/java/com/alipay/sofa/rpc/registry/mesh/MeshApiClientTest.java
  extension-impl/registry-mesh/src/test/java/com/alipay/sofa/rpc/registry/mesh/mock/HttpMockServer.java
  extension-impl/registry-zk/src/test/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistryDestroyTest.java
  extension-impl/registry-zk/src/test/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistryHelperTest.java
  extension-impl/registry-zk/src/test/java/com/alipay/sofa/rpc/registry/zk/base/BaseZkTest.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/server/http/AbstractHttpServer.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/Http2ClientInitializer.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/Http2ServerUpgradeHandler.java
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/RestTracerAdapter.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/RpcSofaTracer.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/factory/MemoryReporterImpl.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/factory/ReporterFactory.java
  extension-impl/tracer-opentracing/src/test/java/com/alipay/sofa/rpc/tracer/sofatracer/RpcSofaTracerTest.java
  extension-impl/tracer-opentracing/src/test/java/com/alipay/sofa/rpc/tracer/sofatracer/log/stat/RpcClientStatTest.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubboServerTest.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/registry/base/BaseZkTest.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/registry/zk/OverrideService.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/registry/zk/OverrideServiceImpl.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/registry/zk/WarmUpService.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/registry/zk/WarmUpServiceImpl.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/client/bolt/BoltExceptionTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/tracer/util/TracerChecker.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/transport/http/Http2ClearTextPriorKnowledgeTest.java
Labels: optimization

#393 Optimize imports and authors.
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/ElasticConnectionHolder.java
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/SingleGroupAddressHolder.java
  core-impl/client/src/test/java/com/alipay/sofa/rpc/client/lb/ConsistentHashLoadBalancerTest.java
  core-impl/client/src/test/java/com/alipay/sofa/rpc/client/lb/WeightConsistentHashLoadBalancerTest.java
  core-impl/client/src/test/java/com/alipay/sofa/rpc/client/lb/WeightRoundRobinLoadBalancerTest.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcConstants.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/json/BeanSerializer.java
  extension-impl/bootstrap-dubbo/src/main/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubboProviderBootstrap.java
  extension-impl/bootstrap-dubbo/src/test/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubooServerTest.java
  extension-impl/bootstrap-dubbo/src/test/java/com/alipay/sofa/rpc/bootstrap/dubbo/demo/DemoServiceImpl.java
  extension-impl/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SofaHessianSerializer.java
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/registry/utils/RegistryUtils.java
  extension-impl/extension-common/src/test/java/com/alipay/sofa/rpc/bootstrap/DefaultProviderBootstrapTest.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/FaultBaseServiceTest.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/FaultBaseTest.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/bean/FaultHelloService.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/bean/FaultHelloService2.java
  extension-impl/log-common-tools/src/test/java/com/alipay/sofa/rpc/log/factory/RpcLoggerFactoryTest.java
  extension-impl/metrics-lookout/src/main/java/com/alipay/sofa/rpc/event/LookoutSubscriber.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/model/ConsulService.java
  extension-impl/registry-consul/src/test/java/com/alipay/sofa/rpc/registry/consul/ConsulRegistryTest.java
  extension-impl/registry-local/src/test/java/com/alipay/sofa/rpc/registry/local/LocalRegistryHelperTest.java
  extension-impl/registry-nacos/src/main/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistry.java
  extension-impl/registry-nacos/src/main/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistryHelper.java
  extension-impl/registry-nacos/src/main/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistryProviderObserver.java
  extension-impl/registry-nacos/src/test/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistryTest.java
  extension-impl/registry-nacos/src/test/java/com/alipay/sofa/rpc/registry/nacos/base/BaseNacosTest.java
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperConfigObserver.java
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperOverrideObserver.java
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperProviderObserver.java
  extension-impl/registry-zk/src/test/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistryDestroyTest.java
  extension-impl/registry-zk/src/test/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistryHelperTest.java
  extension-impl/registry-zk/src/test/java/com/alipay/sofa/rpc/registry/zk/base/BaseZkTest.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/server/http/AbstractHttpServer.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/Http2ClientInitializer.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/Http2ServerUpgradeHandler.java
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/RestTracerAdapter.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/RpcSofaTracer.java
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/factory/ReporterFactory.java
  extension-impl/tracer-opentracing/src/test/java/com/alipay/sofa/rpc/tracer/sofatracer/RpcSofaTracerTest.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubboServerTest.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/registry/base/BaseZkTest.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/registry/zk/OverrideService.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/registry/zk/OverrideServiceImpl.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/registry/zk/WarmUpService.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/registry/zk/WarmUpServiceImpl.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/transport/http/Http2ClearTextPriorKnowledgeTest.java
Labels: optimization

#415 optimize async thread pool execute
  core/api/src/main/java/com/alipay/sofa/rpc/event/EventBus.java
Labels: enhancement

#195 add hystrix integration extension
  all/pom.xml
  extension-impl/fault-hystrix/pom.xml
  extension-impl/fault-hystrix/src/main/java/com/alipay/sofa/rpc/hystrix/DefaultFallbackFactory.java
  extension-impl/fault-hystrix/src/main/java/com/alipay/sofa/rpc/hystrix/DefaultSetterFactory.java
  extension-impl/fault-hystrix/src/main/java/com/alipay/sofa/rpc/hystrix/FallbackFactory.java
  extension-impl/fault-hystrix/src/main/java/com/alipay/sofa/rpc/hystrix/HystrixConstants.java
  extension-impl/fault-hystrix/src/main/java/com/alipay/sofa/rpc/hystrix/HystrixFilter.java
  extension-impl/fault-hystrix/src/main/java/com/alipay/sofa/rpc/hystrix/HystrixResponseFuture.java
  extension-impl/fault-hystrix/src/main/java/com/alipay/sofa/rpc/hystrix/SetterFactory.java
  extension-impl/fault-hystrix/src/main/java/com/alipay/sofa/rpc/hystrix/SofaHystrixCommand.java
  extension-impl/fault-hystrix/src/main/java/com/alipay/sofa/rpc/hystrix/SofaHystrixConfig.java
  extension-impl/fault-hystrix/src/main/java/com/alipay/sofa/rpc/hystrix/SofaHystrixInvokable.java
  extension-impl/fault-hystrix/src/main/java/com/alipay/sofa/rpc/hystrix/SofaHystrixObservableCommand.java
  extension-impl/fault-hystrix/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.filter.Filter
  extension-impl/pom.xml
  test/test-integration/pom.xml
  test/test-integration/src/test/java/com/alipay/sofa/rpc/hystrix/HelloServiceFallback.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/hystrix/HelloServiceFallbackFactory.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/hystrix/HystrixFilterAsyncTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/hystrix/HystrixFilterSyncTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/hystrix/InvokeFailedHelloService.java
Labels: enhancement

#439 Make resteasy execute rpc filter chain too.
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/RestServer.java
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/SofaResourceFactory.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/rest/ClientRequestTestFilter.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/rest/CustomizeClientRequestTestFilter.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/rest/CustomizeClientResponseTestFilter.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/rest/CustomizeContainerRequestTestFilter.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/rest/CustomizeContainerResponseTestFilter.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/rest/CustomizeFilterTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/rest/CustomizeTestFilter.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/rest/RestTracerTest.java
Labels: optimization

#454 Fix consul converter and construct props order
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/common/ConsulURL.java
Labels: bug

#239 Support jackson serialize
  all/pom.xml
  extension-impl/codec-jackson/pom.xml
  extension-impl/codec-jackson/src/main/java/com/alipay/sofa/rpc/codec/jackson/JacksonHelper.java
  extension-impl/codec-jackson/src/main/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializer.java
  extension-impl/codec-jackson/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.codec.Serializer
  extension-impl/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializerTest.java
  extension-impl/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/model/DemoRequest.java
  extension-impl/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/model/DemoResponse.java
  extension-impl/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/model/DemoService.java
  extension-impl/codec-jackson/src/test/resources/log4j.xml
  extension-impl/codec-jackson/src/test/resources/sofa-rpc/rpc-config.json
  extension-impl/pom.xml
  test/test-integration/pom.xml
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/http/Http1ServerTest.java
Labels: extension
