Repository sofastack/sofa-rpc, pull requests merged in 2018-07, with the labels that each got.

#212 Change version to 5.4.3-SNAPSHOT
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: upgrade

#219 Incorrectly provider list notified when scanning file changes.
  extension-impl/registry-local/src/main/java/com/alipay/sofa/rpc/registry/local/LocalRegistry.java
  extension-impl/registry-local/src/test/java/com/alipay/sofa/rpc/registry/local/LocalRegistryTest.java
Labels: bug

#222 Use multiple separate counters for the single service with multiple protocols.
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/bootstrap/DefaultProviderBootstrap.java
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistryHelper.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/multi/MultiProtolServerTest.java
Labels: optimization

#227 Prepare to release v5.4.3.
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: upgrade

#230 Change document url from wiki to sofastack.tech.
  README.md
  README_EN.md
Labels: document

#231 Incorrect provider list notified when scanning file changes.
  extension-impl/registry-local/src/main/java/com/alipay/sofa/rpc/registry/local/LocalRegistry.java
  extension-impl/registry-local/src/test/java/com/alipay/sofa/rpc/registry/local/LocalRegistryTest.java
Labels: bug

#233 Change version to 5.4.4-SNAPSHOT.
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: upgrade

#235 Modify incorrect comments and improve map traversal efficiency in BeanSerializer.
  core/common/src/main/java/com/alipay/sofa/rpc/common/cache/ReflectCache.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/json/BeanSerializer.java
  core/common/src/test/java/com/alipay/sofa/rpc/common/json/BeanSerializerTest.java
Labels: enhancement
