Repository sofastack/sofa-rpc, pull requests merged in 2018-09, with the labels that each got.

#289 Fix unstable test cases.
  extension-impl/registry-mesh/src/test/java/com/alipay/sofa/rpc/registry/mesh/BaseMeshTest.java
  extension-impl/registry-mesh/src/test/java/com/alipay/sofa/rpc/registry/mesh/MeshApiClientTest.java
  extension-impl/registry-mesh/src/test/java/com/alipay/sofa/rpc/registry/mesh/MeshRegistryTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/multi/MultiProtocolServerExpTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/multi/MultiProtocolServerTest.java
Labels: optimization

#293 Fix incorrect version of dependencies.
  bom/pom.xml
Labels: optimization

#298 Optimize string contact.
  core-impl/proxy/src/main/java/com/alipay/sofa/rpc/proxy/javassist/JavassistProxy.java
Labels: optimization

#299 Upgrade version to 5.4.6-SNAPSHOT.
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-mesh/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: upgrade

#308 Fix unexpected provider operation cause by unordered zookeeper event.
  .travis.yml
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperConfigObserver.java
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperOverrideObserver.java
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperProviderObserver.java
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistry.java
  extension-impl/registry-zk/src/test/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistryTest.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/registry/zk/ZookeeperServerRestartTest.java
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/registry/zk/ZookeeperSubscribeObserverTest.java
Labels: bug

#313 Code clean up.
  all/pom.xml
  core-impl/client/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.client.LoadBalancer
  core/common/src/main/java/com/alipay/sofa/rpc/common/utils/CodecUtils.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/utils/CommonUtils.java
  core/common/src/test/java/com/alipay/sofa/rpc/common/utils/CodecUtilsTest.java
  extension-impl/pom.xml
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/common/ConsulURL.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/common/ConsulURLUtils.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/internal/ConsulManager.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/internal/TtlScheduler.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/model/ConsulEphemeralNode.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/model/ConsulSession.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/model/HeartbeatService.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/model/ThrallRoleType.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/transport/bolt/BoltClientConnectionManager.java
Labels: optimization

#315 Upgrade hessian to v3.3.3.
  all/pom.xml
  bom/pom.xml
  extension-impl/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SofaHessianSerializer.java
  extension-impl/codec-sofa-hessian/src/main/resources/sofa-rpc/serialize_blacklist.txt
  extension-impl/codec-sofa-hessian/src/test/java/com/alipay/sofa/rpc/codec/sofahessian/BlackListFileLoaderTest.java
Labels: upgrade

#320 update version to 5.4.6 to release
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-mesh/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: upgrade

#324 Code clean up.
  bom/pom.xml
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AllConnectConnectionHolder.java
  core/api/src/main/java/com/alipay/sofa/rpc/client/ConnectionHolder.java
  core/api/src/main/java/com/alipay/sofa/rpc/codec/CompressorFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/codec/SerializerFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/ProviderConfig.java
  core/api/src/main/java/com/alipay/sofa/rpc/ext/ExtensionLoader.java
  core/api/src/test/java/com/alipay/sofa/rpc/codec/CompressorFactoryTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/codec/SerializerFactoryTest.java
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/registry/utils/RegistryUtils.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/server/http/AbstractHttpServerTask.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/server/http/Http2ServerTask.java
Labels: optimization
