Repository sofastack/sofa-rpc, pull requests merged in 2019-05, with the labels that each got.

#605 exclude SofaRegistryTest in this branch
  extension-impl/registry-sofa/pom.xml
Labels: ci/cd

#617 Enhance service generation of Nacos Registry
  extension-impl/registry-nacos/src/main/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistry.java
  extension-impl/registry-nacos/src/main/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistryHelper.java
  extension-impl/registry-nacos/src/main/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistryProviderObserver.java
  extension-impl/registry-nacos/src/test/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistryHelperTest.java
Labels: enhancement

#634 Fix link address.
  README.md
  README_zh_CN.md
Labels: document
