Repository sofastack/sofa-rpc, pull requests merged in 2019-02, with the labels that each got.

#497 Make RpcConfigs.getOrDefaultValue compatible multiple types.
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcConfigs.java
  core/api/src/test/java/com/alipay/sofa/rpc/common/RpcConfigsTest.java
Labels: bug

#511 Support bytebuddy as proxy
  all/pom.xml
  bom/pom.xml
  core-impl/proxy/pom.xml
  core-impl/proxy/src/main/java/com/alipay/sofa/rpc/proxy/bytebuddy/BytebuddyInvocationHandler.java
  core-impl/proxy/src/main/java/com/alipay/sofa/rpc/proxy/bytebuddy/BytebuddyProxy.java
  core-impl/proxy/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.proxy.Proxy
  core-impl/proxy/src/test/java/com/alipay/sofa/rpc/proxy/bytebuddy/BytebuddyProxyTest.java
Labels: extension

#515 do not registe cors filter if user can not set
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/RestServer.java
Labels: optimization

#506 do not catch exception when registerProcessor
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/RestServer.java
Labels: defects

#501 Automatic fault tolerance module change to extension mode.
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcOptions.java
  core/api/src/test/java/com/alipay/sofa/rpc/ext/WrongProtocol.java
  extension-impl/fault-tolerance/src/main/java/com/alipay/sofa/rpc/client/aft/DegradeStrategy.java
  extension-impl/fault-tolerance/src/main/java/com/alipay/sofa/rpc/client/aft/MeasureResultDetail.java
  extension-impl/fault-tolerance/src/main/java/com/alipay/sofa/rpc/client/aft/MeasureStrategy.java
  extension-impl/fault-tolerance/src/main/java/com/alipay/sofa/rpc/client/aft/RecoverStrategy.java
  extension-impl/fault-tolerance/src/main/java/com/alipay/sofa/rpc/client/aft/RegulationStrategy.java
  extension-impl/fault-tolerance/src/main/java/com/alipay/sofa/rpc/client/aft/Regulator.java
  extension-impl/fault-tolerance/src/main/java/com/alipay/sofa/rpc/client/aft/impl/TimeWindowRegulator.java
  extension-impl/fault-tolerance/src/main/java/com/alipay/sofa/rpc/client/aft/impl/WeightDegradeStrategy.java
  extension-impl/fault-tolerance/src/main/java/com/alipay/sofa/rpc/module/FaultToleranceModule.java
  extension-impl/fault-tolerance/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.client.aft.DegradeStrategy
  extension-impl/fault-tolerance/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.client.aft.MeasureStrategy
  extension-impl/fault-tolerance/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.client.aft.RecoverStrategy
  extension-impl/fault-tolerance/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.client.aft.RegulationStrategy
  extension-impl/fault-tolerance/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.client.aft.Regulator
Labels: extension, optimization

#507 when consumer has not timeout,use timeout of provider
  core/api/src/main/java/com/alipay/sofa/rpc/config/ConsumerConfig.java
  core/common/src/main/resources/com/alipay/sofa/rpc/common/rpc-config-default.json
Labels: enhancement

#509 support reuse and do not reuse connection for bolt
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/transport/bolt/AloneBoltClientConnectionManager.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/transport/bolt/BoltClientConnectionManager.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/transport/bolt/BoltClientTransport.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/transport/bolt/ReuseBoltClientConnectionManager.java
  extension-impl/remoting-bolt/src/test/java/com/alipay/sofa/rpc/transport/bolt/BoltClientTransportTest.java
  extension-impl/remoting-bolt/src/test/java/com/alipay/sofa/rpc/transport/bolt/ReuseBoltClientConnectionManagerTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/client/AllConnectConnectionHolderTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/client/LazyConnectTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/client/ReconnectTest.java
Labels: defects, optimization

#522 fix nacos bug
  extension-impl/registry-nacos/src/main/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistry.java
  extension-impl/registry-nacos/src/test/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistryNamespaceTest.java
Labels: bug

#524 update rpc to 5.5.1 to prepare release
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-jackson/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-hystrix/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-consul/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-mesh/pom.xml
  extension-impl/registry-nacos/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: upgrade

#528 update version to 5.5.2-SNAPSHOT
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-jackson/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-hystrix/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-consul/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-mesh/pom.xml
  extension-impl/registry-nacos/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: upgrade
