Repository sofastack/sofa-rpc, pull requests merged in 2019-10, with the labels that each got.

#773 Upgrade jackson version
  bom/pom.xml
Labels: cla:yes, size/XS

#777 change default connection timeout 1000ms
  core/common/src/main/resources/com/alipay/sofa/rpc/common/rpc-config-default.json
  extension-impl/extension-common/src/main/resources/sofa-rpc/rpc-config.json
Labels: cla:yes, size/XS

#784 change version 559 snapshot
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-jackson/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-hystrix/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-consul/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-mesh/pom.xml
  extension-impl/registry-nacos/pom.xml
  extension-impl/registry-sofa/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: cla:yes, size/M

#785 change rpc version 5.5.9
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-jackson/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-hystrix/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-consul/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-mesh/pom.xml
  extension-impl/registry-nacos/pom.xml
  extension-impl/registry-sofa/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: size/M, upgrade

#770 H2 TLS security support
  all/pom.xml
  bom/pom.xml
  example/pom.xml
  example/src/test/java/com/alipay/sofa/rpc/http2/Http2WithSSLClientMain.java
  example/src/test/java/com/alipay/sofa/rpc/http2/Http2WithSSLServerMain.java
  example/src/test/resources/privatekey.key
  example/src/test/resources/selfSigned.crt
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/server/http/Http2WithSSLServer.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/Http2ClientInitializer.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/Http2WithSSLServerTransport.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/SelfSignedCer.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/SslContextBuilder.java
  extension-impl/remoting-http/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.server.Server
  extension-impl/remoting-http/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.transport.ServerTransport
Labels: First-time contributor, cla:yes, size/XL, waiting-for-feedback

#783 Fix data util test when run in a Daylight Saving Time
  core/common/src/test/java/com/alipay/sofa/rpc/common/utils/DateUtilsTest.java
Labels: bug, cla:yes, question, size/M

#789 update netty 4.1.42
  all/pom.xml
Labels: cla:yes, size/XS
