Repository sofastack/sofa-rpc, pull requests merged in 2019-11, with the labels that each got.

#793 chore:update rpc version to 5.6.3 snapshot
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-jackson/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-protostuff/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-hystrix/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-consul/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-mesh/pom.xml
  extension-impl/registry-nacos/pom.xml
  extension-impl/registry-sofa/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: cla:yes, size/M

#794 chore:fix alert for jackson-databind
  bom/pom.xml
Labels: bug, cla:yes, size/XS

#792 chore:remove fetch group name
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/SingleGroupAddressHolder.java
  core-impl/client/src/test/java/com/alipay/sofa/rpc/client/SingleGroupAddressHolderTest.java
  core/api/src/main/java/com/alipay/sofa/rpc/client/AddressHolder.java
  core/api/src/test/java/com/alipay/sofa/rpc/client/TestAddressHolder.java
Labels: cla:yes, size/L

#795 bugfix:fix npe of AbstractCluster
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
Labels: bug, cla:yes, size/XS

#796 bugfix:fix npe of AbstractCluster
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
Labels: bug, cla:yes, size/XS

#800 feat:add custom parameter to values
  extension-impl/registry-local/src/main/java/com/alipay/sofa/rpc/registry/local/LocalRegistryHelper.java
Labels: cla:yes, size/XS

#712 Enable baggage-items for rpc reseteasy mode
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/RestTracerAdapter.java
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/transport/rest/TraceClientRequestFilter.java
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/transport/rest/TraceClientResponseFilter.java
Labels: cla:yes, size/L, waiting-for-feedback

#799 feat:add some headers to sofa request
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/codec/bolt/SofaRpcSerialization.java
Labels: cla:yes, size/XS

#716 Support GRPC
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/config/ConsumerConfig.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/ProviderConfig.java
  example/pom.xml
  example/src/main/java/com/alipay/sofa/rpc/grpc/examples/registry/GreeterImpl.java
  example/src/main/java/com/alipay/sofa/rpc/grpc/examples/registry/GrpcClientRegistryApplication.java
  example/src/main/java/com/alipay/sofa/rpc/grpc/examples/registry/GrpcServerRegistryApplication.java
  example/src/main/proto/helloworld.proto
  extension-impl/bootstrap-grpc/pom.xml
  extension-impl/bootstrap-grpc/src/main/java/com/dib/sofa/rpc/bootstrap/grpc/GrpcConsumerBootstrap.java
  extension-impl/bootstrap-grpc/src/main/java/com/dib/sofa/rpc/bootstrap/grpc/GrpcProviderBootstrap.java
  extension-impl/bootstrap-grpc/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.bootstrap.ConsumerBootstrap
  extension-impl/bootstrap-grpc/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.bootstrap.ProviderBootstrap
  extension-impl/bootstrap-grpc/src/test/resources/log4j.xml
  extension-impl/bootstrap-grpc/src/test/resources/sofa-rpc/rpc-config.json
  extension-impl/pom.xml
  extension-impl/remoting-grpc/pom.xml
  extension-impl/remoting-grpc/src/main/java/com/alipay/sofa/rpc/server/grpc/GrpcServer.java
  extension-impl/remoting-grpc/src/main/java/com/alipay/sofa/rpc/transport/grpc/GrpcClientInvoker.java
  extension-impl/remoting-grpc/src/main/java/com/alipay/sofa/rpc/transport/grpc/GrpcClientTransport.java
  extension-impl/remoting-grpc/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.server.Server
  extension-impl/remoting-grpc/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.transport.ClientTransport
  extension-impl/remoting-grpc/src/test/resources/log4j.xml
  extension-impl/remoting-grpc/src/test/resources/sofa-rpc/rpc-config.json
Labels: First-time contributor, cla:yes, size/XXL

#788 support msgpack serialization
  all/pom.xml
  bom/pom.xml
  example/src/test/java/com/alipay/sofa/rpc/msgpack/HelloService.java
  example/src/test/java/com/alipay/sofa/rpc/msgpack/HelloServiceImpl.java
  example/src/test/java/com/alipay/sofa/rpc/msgpack/QuickStartClient.java
  example/src/test/java/com/alipay/sofa/rpc/msgpack/QuickStartServer.java
  extension-impl/codec-msgpack/pom.xml
  extension-impl/codec-msgpack/src/main/java/com/alipay/sofa/rpc/codec/msgpack/MsgPackHelper.java
  extension-impl/codec-msgpack/src/main/java/com/alipay/sofa/rpc/codec/msgpack/MsgPackSerializer.java
  extension-impl/codec-msgpack/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.codec.Serializer
  extension-impl/codec-msgpack/src/test/java/com/alipay/sofa/rpc/codec/msgpack/MsgPackSerializerTest.java
  extension-impl/codec-msgpack/src/test/java/com/alipay/sofa/rpc/codec/msgpack/model/DemoRequest.java
  extension-impl/codec-msgpack/src/test/java/com/alipay/sofa/rpc/codec/msgpack/model/DemoResponse.java
  extension-impl/codec-msgpack/src/test/java/com/alipay/sofa/rpc/codec/msgpack/model/DemoService.java
  extension-impl/codec-msgpack/src/test/resources/log4j.xml
  extension-impl/codec-msgpack/src/test/resources/sofa-rpc/rpc-config.json
  extension-impl/pom.xml
Labels: cla:yes, size/XXL

#802 chore:update hessian 3.3.7 snapshot
  all/pom.xml
  bom/pom.xml
Labels: cla:yes, size/M

#803 fix:fix msgpack dep
  all/pom.xml
Labels: bug, cla:yes, size/XS

#808 fix:fix simple map serializer
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/codec/bolt/SimpleMapSerializer.java
Labels: bug, cla:yes, size/M

#809 test:add compatible test case
  extension-impl/remoting-bolt/src/test/java/com/alipay/sofa/rpc/codec/bolt/SimpleMapSerializerTest.java
Labels: cla:yes, size/M
