Repository sofastack/sofa-rpc, pull requests merged in 2019-06, with the labels that each got.

#386 update zk to 4.0.1 to support spring cloud
  bom/pom.xml
  extension-impl/registry-mesh/src/test/java/com/alipay/sofa/rpc/registry/mesh/MeshApiClientTest.java
Labels: jdk8

#669 Fix travis ci install jdk failed
  .travis.yml
Labels: ci/cd

#673 remove unused code
  core/api/src/main/java/com/alipay/sofa/rpc/client/ProviderInfoAttrs.java
  extension-impl/registry-sofa/src/main/java/com/alipay/sofa/rpc/registry/sofa/SofaRegistry.java
  extension-impl/registry-sofa/src/main/java/com/alipay/sofa/rpc/registry/sofa/SofaRegsitryClient.java
Labels: optimization
