Repository sofastack/sofa-rpc, pull requests merged in 2019-09, with the labels that each got.

#746 register ServerStoppedEvent to LookoutModule course LookoutSubscriber…
  extension-impl/metrics-lookout/src/main/java/com/alipay/sofa/rpc/module/LookoutModule.java
Labels: First-time contributor, cla:no, size/XS

#756 change rpc version to 5.6.2 snapshot
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-jackson/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-protostuff/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-hystrix/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-consul/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-mesh/pom.xml
  extension-impl/registry-nacos/pom.xml
  extension-impl/registry-sofa/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: cla:yes, size/M

#749 fix mesh
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/MeshRegistry.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/MeshRegistryHelper.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/SofaRegistryConstants.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/SofaRegistryHelper.java
Labels: bug, cla:yes, size/XL

#758 fixed path error
  extension-impl/codec-protostuff/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.codec.Serializer
Labels: First-time contributor, cla:yes, size/XS

#765 make log4j2 aysnc
  extension-impl/log-common-tools/src/main/resources/com/alipay/sofa/rpc/log/log4j2/log-conf.xml
Labels: cla:yes, size/M

#766 fix invoke timeout for generic invoke,when user set the genericcontext
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/filter/ConsumerGenericFilter.java
Labels: bug, cla:yes, question, size/XS

#768 Fix generic invoke method name
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/RpcSofaTracer.java
Labels: bug, cla:yes, size/XS

#760 change rpc 5.6.2
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-jackson/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-protostuff/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-hystrix/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-consul/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-mesh/pom.xml
  extension-impl/registry-nacos/pom.xml
  extension-impl/registry-sofa/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: cla:yes, size/M

#771 fix local address
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/transport/bolt/BoltClientTransport.java
Labels: bug, cla:yes, size/XS

#772 prepare release 5.5.8
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-jackson/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-hystrix/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-consul/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-mesh/pom.xml
  extension-impl/registry-nacos/pom.xml
  extension-impl/registry-sofa/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: cla:yes, size/M
