Repository sofastack/sofa-rpc, pull requests merged in 2019-12, with the labels that each got.

#812 feat:usually we do not open the switch of sec or blacklist
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AllConnectConnectionHolder.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcOptions.java
  core/common/src/main/resources/com/alipay/sofa/rpc/common/rpc-config-default.json
Labels: cla:yes, size/M

#811 chore:print extension loader debug info instead of error
  core/api/src/main/java/com/alipay/sofa/rpc/ext/ExtensionLoader.java
Labels: cla:yes, size/S

#807 support non-registered center ip for direct connection
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AllConnectConnectionHolder.java
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/FailoverCluster.java
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/SingleGroupAddressHolder.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcOptions.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/ConsumerConfig.java
  core/api/src/main/java/com/alipay/sofa/rpc/transport/ClientTransportConfig.java
  core/common/src/main/resources/com/alipay/sofa/rpc/common/rpc-config-default.json
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/client/FailoverClusterTest.java
Labels: cla:yes, size/L

#813 chore:optimize code normally
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AllConnectConnectionHolder.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/ConsumerConfig.java
Labels: cla:yes, size/M

#817 update rpc version to 5.6.3
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-grpc/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-jackson/pom.xml
  extension-impl/codec-msgpack/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-protostuff/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-hystrix/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-consul/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-mesh/pom.xml
  extension-impl/registry-nacos/pom.xml
  extension-impl/registry-sofa/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-grpc/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: First-time contributor, cla:yes, size/L

#819 chore:update hessian 3.3.7
  all/pom.xml
  bom/pom.xml
Labels: cla:yes, size/XS

#823 chore:update version
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-grpc/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-jackson/pom.xml
  extension-impl/codec-msgpack/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-protostuff/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-hystrix/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-consul/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-mesh/pom.xml
  extension-impl/registry-nacos/pom.xml
  extension-impl/registry-sofa/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-grpc/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: cla:yes, size/L

#822 Feat/tracer fix
  all/pom.xml
  bom/pom.xml
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/RpcSofaTracer.java
Labels: bug, cla:yes, size/S

#827 RPC Multi-Version
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcConstants.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/codec/bolt/SofaRpcSerialization.java
Labels: cla:yes, size/XS

#824 Feat/update dubbo
  bom/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-dubbo/src/main/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubboConvertor.java
  extension-impl/bootstrap-dubbo/src/main/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubboSingleton.java
Labels: cla:yes, size/S

#816 Feat/optimize grpc
  core/api/src/main/java/com/alipay/sofa/rpc/config/ProviderConfig.java
  example/src/test/java/com/alipay/sofa/rpc/grpc/GreeterImpl.java
  example/src/test/java/com/alipay/sofa/rpc/grpc/GrpcClientRegistryApplication.java
  example/src/test/java/com/alipay/sofa/rpc/grpc/GrpcServerRegistryApplication.java
  extension-impl/bootstrap-grpc/pom.xml
  extension-impl/bootstrap-grpc/src/main/java/com/alipay/sofa/rpc/bootstrap/grpc/GrpcConsumerBootstrap.java
  extension-impl/bootstrap-grpc/src/main/java/com/alipay/sofa/rpc/bootstrap/grpc/GrpcProviderBootstrap.java
  extension-impl/bootstrap-grpc/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.bootstrap.ConsumerBootstrap
  extension-impl/bootstrap-grpc/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.bootstrap.ProviderBootstrap
  extension-impl/remoting-grpc/src/main/java/com/alipay/sofa/rpc/transport/grpc/GrpcClientInvoker.java
  extension-impl/remoting-grpc/src/main/java/com/alipay/sofa/rpc/transport/grpc/GrpcClientTransport.java
  test/test-integration/pom.xml
  test/test-integration/src/main/proto/helloworld.proto
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/grpc/GreeterImpl.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/grpc/GrpcServerTest.java
Labels: cla:yes, size/L

#830 chore:manage sofa rpc version
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  .travis.yml
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-grpc/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-jackson/pom.xml
  extension-impl/codec-msgpack/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-protostuff/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-hystrix/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-consul/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-mesh/pom.xml
  extension-impl/registry-nacos/pom.xml
  extension-impl/registry-sofa/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-grpc/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  mvnw
  mvnw.cmd
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
  tools/change_version.sh
Labels: cla:yes, size/XL

#831 fix:fix version manager
  all/pom.xml
  tools/change_version.sh
Labels: bug, cla:yes, size/M

#832 chore:update netty version 4.1.44.final
  all/pom.xml
  bom/pom.xml
Labels: cla:yes, size/XS

#834 fix:fix the default sampled of tracer
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/RpcSofaTracer.java
Labels: bug, cla:yes, size/XS

#836 feat:optimize the tracer code
  extension-impl/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/RpcSofaTracer.java
Labels: cla:yes, size/S
