Repository sofastack/sofa-rpc, pull requests merged in 2019-07, with the labels that each got.

#707 add set method of providerBootStrap
  core/api/src/main/java/com/alipay/sofa/rpc/config/ProviderConfig.java
Labels: cla:yes, size/XS

#708 Upgrade 5.5.7 snapshot
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/codec/pom.xml
  core-impl/filter/pom.xml
  core-impl/log/pom.xml
  core-impl/pom.xml
  core-impl/proxy/pom.xml
  core-impl/transport/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  core/common/pom.xml
  core/exception/pom.xml
  core/pom.xml
  example/pom.xml
  extension-impl/api-compatible/pom.xml
  extension-impl/bootstrap-bolt/pom.xml
  extension-impl/bootstrap-dubbo/pom.xml
  extension-impl/bootstrap-http/pom.xml
  extension-impl/bootstrap-rest/pom.xml
  extension-impl/codec-jackson/pom.xml
  extension-impl/codec-protobuf/pom.xml
  extension-impl/codec-sofa-hessian/pom.xml
  extension-impl/extension-common/pom.xml
  extension-impl/fault-hystrix/pom.xml
  extension-impl/fault-tolerance/pom.xml
  extension-impl/log-common-tools/pom.xml
  extension-impl/metrics-lookout/pom.xml
  extension-impl/pom.xml
  extension-impl/registry-consul/pom.xml
  extension-impl/registry-local/pom.xml
  extension-impl/registry-mesh/pom.xml
  extension-impl/registry-nacos/pom.xml
  extension-impl/registry-sofa/pom.xml
  extension-impl/registry-zk/pom.xml
  extension-impl/remoting-bolt/pom.xml
  extension-impl/remoting-http/pom.xml
  extension-impl/remoting-resteasy/pom.xml
  extension-impl/tracer-opentracing-resteasy/pom.xml
  extension-impl/tracer-opentracing/pom.xml
  pom.xml
  test/pom.xml
  test/test-common/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration/pom.xml
Labels: cla:yes, size/M

#709 Destroy server config
  core/api/src/main/java/com/alipay/sofa/rpc/config/ServerConfig.java
  core/api/src/main/java/com/alipay/sofa/rpc/server/ServerFactory.java
  core/api/src/test/java/com/alipay/sofa/rpc/server/ServerFactoryTest.java
Labels: cla:yes, size/S

#723 upgrade jackson version 2.9.9 to 2.9.9.1
  bom/pom.xml
Labels: cla:yes, size/XS
