Repository sofastack/sofa-rpc, pull requests merged in 2020-02, with the labels that each got.

#854 chore:update rpc version 5.6.4
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/XS

#855 chore:update rpc version 5.6.5-snapshot
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/S

#846 Support Bolt swagger
  all/pom.xml
  bom/pom.xml
  example/pom.xml
  example/src/test/java/com/alipay/sofa/rpc/bolt/start/BoltServerMainWithSwagger.java
  extension-impl/doc-swagger/pom.xml
  extension-impl/doc-swagger/src/main/java/com/alipay/sofa/rpc/doc/swagger/generate/GenerateService.java
  extension-impl/doc-swagger/src/main/java/com/alipay/sofa/rpc/doc/swagger/generate/Reader.java
  extension-impl/doc-swagger/src/main/java/com/alipay/sofa/rpc/doc/swagger/generate/ReaderContext.java
  extension-impl/doc-swagger/src/main/java/com/alipay/sofa/rpc/doc/swagger/generate/ReaderExtension.java
  extension-impl/doc-swagger/src/main/java/com/alipay/sofa/rpc/doc/swagger/generate/RpcReaderExtension.java
  extension-impl/doc-swagger/src/main/java/com/alipay/sofa/rpc/doc/swagger/rest/SwaggerRestService.java
  extension-impl/doc-swagger/src/main/java/com/alipay/sofa/rpc/doc/swagger/rest/SwaggerRestServiceImpl.java
  extension-impl/doc-swagger/src/main/java/com/alipay/sofa/rpc/doc/swagger/utils/ClassUtils.java
  extension-impl/doc-swagger/src/main/java/com/alipay/sofa/rpc/doc/swagger/utils/LocalVariableTableParameterNameDiscoverer.java
  extension-impl/doc-swagger/src/test/java/com/alipay/sofa/rpc/doc/swagger/generate/ReaderTest.java
  extension-impl/doc-swagger/src/test/java/com/alipay/sofa/rpc/doc/swagger/resource/ComplexPojo.java
  extension-impl/doc-swagger/src/test/java/com/alipay/sofa/rpc/doc/swagger/resource/ComplexPojo2.java
  extension-impl/doc-swagger/src/test/java/com/alipay/sofa/rpc/doc/swagger/resource/TestGenerate.java
  extension-impl/doc-swagger/src/test/java/com/alipay/sofa/rpc/doc/swagger/resource/TestSwaggerService.java
  extension-impl/doc-swagger/src/test/java/com/alipay/sofa/rpc/doc/swagger/resource/TestSwaggerServiceImpl.java
  extension-impl/doc-swagger/src/test/java/com/alipay/sofa/rpc/doc/swagger/utils/DemoClass.java
  extension-impl/doc-swagger/src/test/java/com/alipay/sofa/rpc/doc/swagger/utils/DemoInterface.java
  extension-impl/doc-swagger/src/test/java/com/alipay/sofa/rpc/doc/swagger/utils/LocalVariableTableParameterNameDiscovererTest.java
  extension-impl/doc-swagger/src/test/resources/log4j.xml
  extension-impl/doc-swagger/src/test/resources/sofa-rpc/rpc-config.json
  extension-impl/pom.xml
  extension-impl/registry-consul/src/test/java/com/alipay/sofa/rpc/registry/consul/ConsulRegistryTest.java
  extension-impl/registry-mesh/src/test/java/com/alipay/sofa/rpc/registry/mesh/MeshRegistryTest.java
  extension-impl/registry-nacos/src/test/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistryTest.java
  extension-impl/registry-zk/src/test/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistryTest.java
Labels: cla:yes, size/XXL

#857 feat:error code
  core/api/src/main/java/com/alipay/sofa/rpc/log/LogCodes.java
  core/api/src/main/resources/sofa-rpc/logcodes-common_en.properties
  core/api/src/main/resources/sofa-rpc/logcodes-common_zh_CN.properties
Labels: cla:yes, size/XL

#859 Feat/error code limit
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AllConnectConnectionHolder.java
  core/api/src/main/java/com/alipay/sofa/rpc/filter/FilterChain.java
  core/api/src/main/java/com/alipay/sofa/rpc/log/LogCodes.java
  core/api/src/main/java/com/alipay/sofa/rpc/registry/RegistryFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/server/ServerFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/tracer/Tracers.java
  core/api/src/main/resources/sofa-rpc/logcodes-common_en.properties
  core/api/src/main/resources/sofa-rpc/logcodes-common_zh_CN.properties
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/SofaRestRequestHandler.java
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/LookoutRequestFilter.java
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/TraceRequestFilter.java
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/RestTracerAdapter.java
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/transport/rest/TraceClientRequestFilter.java
Labels: cla:yes, size/L

#866 chore: remove duplicate version definition
  example/pom.xml
  extension-impl/bootstrap-grpc/pom.xml
  extension-impl/registry-sofa/pom.xml
  extension-impl/remoting-grpc/pom.xml
Labels: First-time contributor, cla:no, size/XS

#860 chore:grpc error log
  extension-impl/bootstrap-grpc/src/main/java/com/alipay/sofa/rpc/bootstrap/grpc/GrpcConsumerBootstrap.java
  extension-impl/remoting-grpc/src/main/java/com/alipay/sofa/rpc/transport/grpc/GrpcClientInvoker.java
  extension-impl/remoting-grpc/src/main/java/com/alipay/sofa/rpc/transport/grpc/GrpcClientTransport.java
Labels: cla:yes, size/M

#865 Add more error code
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
  core-impl/proxy/src/main/java/com/alipay/sofa/rpc/proxy/bytebuddy/BytebuddyProxy.java
  core-impl/proxy/src/main/java/com/alipay/sofa/rpc/proxy/javassist/JavassistProxy.java
  core-impl/transport/src/main/java/com/alipay/sofa/rpc/transport/AbstractProxyClientTransport.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcConfigs.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/struct/ScheduledService.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/utils/NetUtils.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/AbstractInterfaceConfig.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/ProviderConfig.java
  core/api/src/main/java/com/alipay/sofa/rpc/dynamic/DynamicConfigManagerFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/ext/ExtensionClass.java
  core/api/src/main/java/com/alipay/sofa/rpc/ext/ExtensionLoader.java
  core/api/src/main/java/com/alipay/sofa/rpc/log/LogCodes.java
  core/api/src/main/java/com/alipay/sofa/rpc/protocol/ProtocolFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/proxy/ProxyFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/registry/RegistryFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/transport/ClientTransportFactory.java
  core/api/src/main/resources/sofa-rpc/logcodes-common_en.properties
  core/api/src/main/resources/sofa-rpc/logcodes-common_zh_CN.properties
  extension-impl/bootstrap-grpc/src/main/java/com/alipay/sofa/rpc/bootstrap/grpc/GrpcProviderBootstrap.java
  extension-impl/codec-jackson/src/main/java/com/alipay/sofa/rpc/codec/jackson/JacksonHelper.java
  extension-impl/codec-msgpack/src/main/java/com/alipay/sofa/rpc/codec/msgpack/MsgPackHelper.java
  extension-impl/codec-protobuf/src/main/java/com/alipay/sofa/rpc/codec/protobuf/ProtobufHelper.java
  extension-impl/codec-protostuff/src/main/java/com/alipay/sofa/rpc/codec/protostuff/ProtostuffHelper.java
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/bootstrap/DefaultClientProxyInvoker.java
  extension-impl/fault-hystrix/src/main/java/com/alipay/sofa/rpc/hystrix/SofaAsyncHystrixCommand.java
  extension-impl/fault-hystrix/src/main/java/com/alipay/sofa/rpc/hystrix/SofaHystrixCommand.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/ConsulRegistry.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/HealthServiceInformer.java
  extension-impl/registry-local/src/main/java/com/alipay/sofa/rpc/registry/local/LocalRegistry.java
  extension-impl/registry-local/src/main/java/com/alipay/sofa/rpc/registry/local/LocalRegistryHelper.java
  extension-impl/registry-nacos/src/main/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistry.java
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistry.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/server/bolt/BoltServer.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/transport/bolt/AloneBoltClientConnectionManager.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/transport/bolt/BoltClientTransport.java
  extension-impl/remoting-grpc/src/main/java/com/alipay/sofa/rpc/server/grpc/GrpcServer.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/server/http/AbstractHttpServer.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/AbstractHttp2ServerTransport.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/Http1ServerChannelHandler.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/Http2ClientChannelHandler.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/HttpTransportUtils.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/SslContextBuilder.java
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/RestServer.java
  extension-impl/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/LookoutRequestFilter.java
Labels: cla:yes, size/XL
