Repository sofastack/sofa-rpc, pull requests merged in 2020-05, with the labels that each got.

#908 Chore/release570
  all/pom.xml
  bom/pom.xml
  compiler/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  example/pom.xml
  pom.xml
  test/test-integration/pom.xml
Labels: cla:yes, size/S

#904 fix(codec-jackson): fix json decode error when parameter is List or Array
  codec/codec-jackson/src/main/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializer.java
  codec/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializerTest.java
  codec/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/model/DemoService.java
Labels: First-time contributor, bug, cla:yes, question, size/L

#911 chore: update version to 5.7.1-SNAPSHOT
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/S

#924 refactor:extract method in AbstractCluster
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
Labels: cla:yes, size/XS

#925 fix:fix jackson bind to 2.9.10.4
  bom/pom.xml
Labels: bug, cla:yes, size/XS

#927 chore:update 572 to release
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/XS
