Repository sofastack/sofa-rpc, pull requests merged in 2020-03, with the labels that each got.

#868 Avoid LogCodes throwing exception
  core/api/src/main/java/com/alipay/sofa/rpc/log/LogCodes.java
  core/api/src/main/resources/sofa-rpc/logcodes-common_en.properties
  core/api/src/main/resources/sofa-rpc/logcodes-common_zh_CN.properties
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/SofaRegistryHelper.java
  extension-impl/registry-sofa/src/main/java/com/alipay/sofa/rpc/registry/sofa/SofaRegistryHelper.java
Labels: cla:yes, size/M

#873 fix(build): extension-common source version and target version
  extension-impl/extension-common/pom.xml
Labels: First-time contributor, bug, cla:yes, size/XS

#874 test:fix test case
  core-impl/transport/src/main/java/com/alipay/sofa/rpc/transport/AbstractProxyClientTransport.java
  core/api/src/main/java/com/alipay/sofa/rpc/client/AddressHolderFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/client/ClusterFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/client/ConnectionHolderFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/client/LoadBalancerFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/AbstractInterfaceConfig.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/ProviderConfig.java
  core/api/src/main/java/com/alipay/sofa/rpc/ext/ExtensionClass.java
  core/api/src/main/java/com/alipay/sofa/rpc/filter/FilterChain.java
  core/api/src/main/java/com/alipay/sofa/rpc/proxy/ProxyFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/registry/RegistryFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/server/ServerFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/tracer/TracerFactory.java
  extension-impl/bootstrap-grpc/src/main/java/com/alipay/sofa/rpc/bootstrap/grpc/GrpcConsumerBootstrap.java
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/bootstrap/DefaultConsumerBootstrap.java
  extension-impl/extension-common/src/main/java/com/alipay/sofa/rpc/bootstrap/DefaultProviderBootstrap.java
  extension-impl/fault-hystrix/src/main/java/com/alipay/sofa/rpc/hystrix/SofaHystrixConfig.java
  extension-impl/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/ConsulRegistry.java
  extension-impl/registry-nacos/src/main/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistry.java
  extension-impl/registry-nacos/src/test/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistryTest.java
  extension-impl/registry-zk/src/main/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistry.java
  extension-impl/registry-zk/src/test/java/com/alipay/sofa/rpc/registry/zk/ZookeeperRegistryTest.java
  extension-impl/remoting-bolt/src/main/java/com/alipay/sofa/rpc/transport/bolt/BoltClientTransport.java
  extension-impl/remoting-grpc/src/main/java/com/alipay/sofa/rpc/server/grpc/GrpcServer.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/server/http/AbstractHttpServer.java
  extension-impl/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/SslContextBuilder.java
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/RestServer.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/hystrix/HystrixFilterAsyncTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/hystrix/HystrixFilterSyncTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/hystrix/HystrixService.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/hystrix/HystrixServiceFallback.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/hystrix/HystrixServiceFallbackFactory.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/hystrix/InvokeCounterHystrixService.java
Labels: bug, cla:yes, size/XL

#867 chore: add code for sofaboot
  core/api/src/main/java/com/alipay/sofa/rpc/log/LogCodes.java
  core/api/src/main/resources/sofa-rpc/logcodes-common_en.properties
  core/api/src/main/resources/sofa-rpc/logcodes-common_zh_CN.properties
Labels: cla:yes, size/S

#872 feat (metrics): Provides simple integration of micrometers.
  all/pom.xml
  bom/pom.xml
  extension-impl/metrics-micrometer/pom.xml
  extension-impl/metrics-micrometer/src/main/java/com/alipay/sofa/rpc/metrics/micrometer/SofaRpcMetrics.java
  extension-impl/metrics-micrometer/src/test/java/com/alipay/sofa/rpc/metrics/micrometer/SofaRpcMetricsTest.java
  extension-impl/pom.xml
  test/test-integration/pom.xml
Labels: First-time contributor, cla:yes, size/XL

#849 feat:use auto load balance
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/lb/AutoLoadBalancer.java
  core-impl/client/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.client.LoadBalancer
  core/api/src/main/java/com/alipay/sofa/rpc/client/LoadBalancerFactory.java
  core/common/src/main/resources/com/alipay/sofa/rpc/common/rpc-config-default.json
Labels: cla:yes, size/M

#876 test:speed up test
  extension-impl/bootstrap-dubbo/src/test/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubooServerTest.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/FaultBaseServiceTest.java
  extension-impl/fault-tolerance/src/test/java/com/alipay/sofa/rpc/client/aft/FaultBaseTest.java
  extension-impl/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/MeshRegistry.java
  extension-impl/registry-mesh/src/test/java/com/alipay/sofa/rpc/registry/mesh/MeshApiClientTest.java
  extension-impl/registry-mesh/src/test/java/com/alipay/sofa/rpc/registry/mesh/MeshRegistryTest.java
  extension-impl/registry-mesh/src/test/java/com/alipay/sofa/rpc/registry/mesh/mock/HttpMockServer.java
  extension-impl/remoting-resteasy/src/test/java/com/alipay/sofa/rpc/server/rest/RestServerTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/rest/RestLookoutTest.java
Labels: cla:yes, size/L

#871 feat(codec-jackson): add more than one parameters feature.
  extension-impl/codec-jackson/src/main/java/com/alipay/sofa/rpc/codec/jackson/JacksonHelper.java
  extension-impl/codec-jackson/src/main/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializer.java
  extension-impl/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializerTest.java
  extension-impl/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/model/DemoService.java
Labels: First-time contributor, cla:yes, size/L

#875 support multicast registry
  all/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/utils/NetUtils.java
  core/api/src/main/java/com/alipay/sofa/rpc/log/LogCodes.java
  core/api/src/main/resources/sofa-rpc/logcodes-common_en.properties
  core/api/src/main/resources/sofa-rpc/logcodes-common_zh_CN.properties
  extension-impl/pom.xml
  extension-impl/registry-multicast/pom.xml
  extension-impl/registry-multicast/src/main/java/com/alipay/sofa/rpc/registry/multicast/MulticastRegistry.java
  extension-impl/registry-multicast/src/main/java/com/alipay/sofa/rpc/registry/multicast/MulticastRegistryHelper.java
  extension-impl/registry-multicast/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.registry.Registry
  extension-impl/registry-multicast/src/test/java/com/alipay/sofa/rpc/registry/multicast/MulticastRegistryTest.java
  extension-impl/registry-multicast/src/test/java/com/alipay/sofa/rpc/registry/multicast/api/HelloService.java
  extension-impl/registry-multicast/src/test/java/com/alipay/sofa/rpc/registry/multicast/api/impl/HelloServiceImpl.java
Labels: cla:yes, size/XL

#850 Integration with apollo
  all/pom.xml
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/lb/AutoLoadBalancer.java
  core/api/src/main/java/com/alipay/sofa/rpc/dynamic/DynamicHelper.java
  extension-impl/dynamic-apollo/pom.xml
  extension-impl/dynamic-apollo/src/main/java/com/alipay/sofa/rpc/dynamic/apollo/ApolloDynamicConfigManager.java
  extension-impl/dynamic-apollo/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.dynamic.DynamicConfigManager
  extension-impl/dynamic-apollo/src/test/java/com/alipay/sofa/rpc/dynamic/apollo/ApolloDynamicConfigManagerTest.java
  extension-impl/dynamic-apollo/src/test/resources/log4j.xml
  extension-impl/pom.xml
  extension-impl/registry-mesh/src/test/java/com/alipay/sofa/rpc/registry/mesh/MeshApiClientTest.java
  test/test-integration/pom.xml
Labels: cla:yes, size/L

#861 feat:local mock
  all/pom.xml
  bom/pom.xml
  core-impl/client/pom.xml
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/http/RpcHttpClient.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/MockMode.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/AbstractInterfaceConfig.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/client/bolt/BoltMockTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/client/bolt/HttpMockServer.java
Labels: cla:yes, size/L

#880 chore:update sofa rpc 5.7.0-snapshot
  .travis.yml
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
  test/test-integration/src/test/java/com/alipay/sofa/rpc/hystrix/HystrixFilterAsyncTest.java
Labels: cla:yes, size/S

#883 update version to 5.6.5
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  extension-impl/config-apollo/pom.xml
  extension-impl/config-apollo/src/main/java/com/alipay/sofa/rpc/dynamic/apollo/ApolloDynamicConfigManager.java
  extension-impl/config-apollo/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.dynamic.DynamicConfigManager
  extension-impl/config-apollo/src/test/java/com/alipay/sofa/rpc/dynamic/apollo/ApolloDynamicConfigManagerTest.java
  extension-impl/config-apollo/src/test/resources/log4j.xml
  extension-impl/pom.xml
  pom.xml
  test/test-integration/pom.xml
Labels: cla:yes, size/S

#886 feat:compiler
  .gitignore
  .travis.yml
  compiler/pom.xml
  example/pom.xml
  pom.xml
  remoting/remoting-grpc/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/GrpcTracerAdapter.java
  test/test-integration/pom.xml
  test/test-integration/src/test/java/com/alipay/sofa/rpc/hystrix/HystrixFilterAsyncTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/grpc/GreeterImpl.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/grpc/GrpcServerTest.java
Labels: cla:yes, size/L
