Repository sofastack/sofa-rpc, pull requests merged in 2020-09, with the labels that each got.

#974 send event when triple server started
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/TripleServer.java
  remoting/remoting-triple/src/test/java/com/alipay/sofa/rpc/server/triple/TripleServerTest.java
Labels: cla:yes, question, size/M

#975 upgrade version to 5.7.6
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/S

#965 feat(codec): support jackson feature configure
  codec/codec-jackson/src/main/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializer.java
  codec/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializerTest.java
  codec/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/model/DemoRequest2.java
Labels: bug, cla:yes, size/L

#976 support custom triple metadata & transform pressure mark
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/common/MetadataHolder.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/filter/PressureMarkTransformFilter.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/GenericServiceImpl.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/TripleHeadKeys.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/TripleServer.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/TracingContextKey.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/TripleTracerAdapter.java
  remoting/remoting-triple/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.filter.Filter
  remoting/remoting-triple/src/test/java/com/alipay/sofa/rpc/filter/PressureMarkTransformFilterTest.java
  remoting/remoting-triple/src/test/java/com/alipay/sofa/rpc/server/triple/GenericServiceImplTest.java
  remoting/remoting-triple/src/test/java/com/alipay/sofa/rpc/utils/SofaProtoUtilsTest.java
Labels: cla:yes, size/L

#981 Feat/triple unique
  compiler/pom.xml
  compiler/src/main/resources/SofaTripleStub.mustache
  example/pom.xml
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/constant/TripleConstant.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/TripleServer.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/transport/triple/TripleClientInvoker.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/utils/SofaProtoUtils.java
  test/test-integration/pom.xml
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/triple/TripleServerTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/triple/TripleHessianInvokeTest.java
Labels: cla:yes, size/L
