Repository sofastack/sofa-rpc, pull requests merged in 2020-06, with the labels that each got.

#940 chore: upgrade version to 5.7.3
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/S

#931 fix:only execute registerCustomSerializer onetime
  remoting/remoting-bolt/src/main/java/com/alipay/sofa/rpc/codec/bolt/SofaRpcSerializationRegister.java
Labels: bug, cla:yes, size/S

#936 fix:fix npe in provider compare
  core/api/src/main/java/com/alipay/sofa/rpc/client/ProviderHelper.java
Labels: bug, cla:yes, size/S

#939 chore: update grpc version
  all/pom.xml
  bom/pom.xml
  bootstrap/bootstrap-triple/pom.xml
  example/pom.xml
  remoting/remoting-triple/pom.xml
  test/test-integration/pom.xml
Labels: cla:yes, size/S

#941 fix:fix io set bug
  remoting/remoting-bolt/src/main/java/com/alipay/sofa/rpc/server/bolt/BoltServerProcessor.java
Labels: bug, cla:yes, size/XS

#934 fix h2 not support multi frame
  remoting/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/Http2ServerChannelHandler.java
Labels: bug, cla:yes, size/S

#946 chore:change codec of ProtostuffSerializer
  codec/codec-protostuff/src/main/java/com/alipay/sofa/rpc/codec/protostuff/ProtostuffSerializer.java
Labels: cla:yes, size/XS

#944 fix warm up end time may be null
  core/api/src/main/java/com/alipay/sofa/rpc/client/ProviderInfo.java
Labels: bug, cla:yes, size/XS

#947 feat:update protobuf-java 3.11.0 to match protoc
  bom/pom.xml
Labels: cla:yes, size/XS

#948 add SofaRequest into RpcInvokeContext
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/interceptor/ServerReqHeaderInterceptor.java
Labels: cla:yes, size/XS

#950 fix: triple hessian returnType is void
  codec/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SofaHessianSerializer.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/GenericServiceImpl.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/transport/triple/TripleClientInvoker.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/triple/Request.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/triple/Response.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/triple/TripleHessianInterface.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/triple/TripleHessianInterfaceImpl.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/triple/TripleHessianInvokeTest.java
Labels: bug, cla:yes, size/L

#949 feat:optimize thread local
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/interceptor/ServerReqHeaderInterceptor.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/GenericServiceImpl.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/TracingContextKey.java
Labels: cla:yes, size/M

#956 Prepare to release 5.7.3
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/XS

#958 feat:allow user set the version of triple
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/TripleTracerAdapter.java
Labels: cla:yes, size/XS

#959 chore:upgrade version to 5.7.4-SNAPHOST
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/S
