Repository sofastack/sofa-rpc, pull requests merged in 2021-12, with the labels that each got.

#1140 fix baggage contains null
  core/api/src/main/java/com/alipay/sofa/rpc/context/RpcInvokeContext.java
  core/api/src/test/java/com/alipay/sofa/rpc/context/RpcInvokeContextTest.java
Labels: bug, cla:yes, size/M

#1144 Deprecate unused logger method
  log-common-tools/src/main/java/com/alipay/sofa/rpc/log/MiddlewareLoggerImpl.java
Labels: cla:yes, size/XS

#1143 fix ProviderConfig setTimeout generic error
  core/api/src/main/java/com/alipay/sofa/rpc/config/ConsumerConfig.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/ProviderConfig.java
Labels: bug, cla:yes, First-time contributor, size/XS

#1146 Fix/baggage null
  core/api/src/main/java/com/alipay/sofa/rpc/context/BaggageResolver.java
  core/api/src/main/java/com/alipay/sofa/rpc/context/RpcInvokeContext.java
  core/api/src/main/java/com/alipay/sofa/rpc/core/util/SafeConcurrentHashMap.java
  core/api/src/test/java/com/alipay/sofa/rpc/context/BaggageResolverTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/core/util/SafeConcurrentHashMapTest.java
Labels: bug, cla:yes, size/L

#1150 fix order comparator overflow
  core/api/src/main/java/com/alipay/sofa/rpc/client/RouterChain.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcConfigs.java
  core/api/src/main/java/com/alipay/sofa/rpc/filter/FilterChain.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/SofaConfigs.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/struct/OrderedComparator.java
  core/common/src/test/java/com/alipay/sofa/rpc/common/struct/OrderedComparatorTest.java
Labels: bug, cla:yes, size/M

#1138 Modify the way we set custom header in triple protocol
  core-impl/filter/src/main/java/com/alipay/sofa/rpc/filter/ConsumerCustomHeaderFilter.java
  core-impl/filter/src/test/java/com/alipay/sofa/rpc/filter/CustomHeaderFilterTest.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/common/MetadataHolder.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/filter/PressureMarkTransformFilter.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/TripleTracerAdapter.java
  remoting/remoting-triple/src/test/java/com/alipay/sofa/rpc/filter/PressureMarkTransformFilterTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/triple/TripleHessianInterface.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/triple/TripleHessianInterfaceImpl.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/triple/TripleHessianInvokeTest.java
Labels: cla:yes, size/L
