Repository sofastack/sofa-rpc, pull requests merged in 2021-11, with the labels that each got.

#1121 Upgrade rpc 581 snapshot
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/S

#1120 Add stable bot
  .github/stable.yml
Labels: cla:yes, size/S

#1108 nacos 注册时优先使用VirtualPort，符合官方文档对ServerConfig的virtualPort的描述
  registry/registry-nacos/src/main/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistryHelper.java
  registry/registry-nacos/src/test/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistryTest.java
Labels: cla:yes, First-time contributor, size/M

#1125 add pmd
  bootstrap/bootstrap-api/src/main/java/com/alipay/sofa/rpc/bootstrap/DefaultProviderBootstrap.java
  bootstrap/bootstrap-bolt/src/main/java/com/alipay/sofa/rpc/bootstrap/bolt/BoltClientProxyInvoker.java
  bootstrap/bootstrap-triple/src/main/java/com/alipay/sofa/rpc/bootstrap/triple/TripleProviderBootstrap.java
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AllConnectConnectionHolder.java
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/SingleGroupAddressHolder.java
  core/api/src/main/java/com/alipay/sofa/rpc/client/AddressHolderFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/client/ClusterFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/AbstractIdConfig.java
  core/api/src/main/java/com/alipay/sofa/rpc/dynamic/DynamicConfigManagerFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/proxy/ProxyFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/registry/RegistryFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/server/ProviderProxyInvoker.java
  core/api/src/main/java/com/alipay/sofa/rpc/tracer/TracerFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/transport/ClientTransportConfig.java
  doc-swagger/src/main/java/com/alipay/sofa/rpc/doc/swagger/generate/Reader.java
  fault/fault-hystrix/src/main/java/com/alipay/sofa/rpc/hystrix/SetterFactory.java
  metrics/metrics-lookout/src/main/java/com/alipay/sofa/rpc/metrics/lookout/RpcLookoutId.java
  pom.xml
  registry/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/SofaRegistryHelper.java
  registry/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/client/MeshApiClient.java
  remoting/remoting-bolt/src/main/java/com/alipay/sofa/rpc/transport/bolt/BoltClientTransport.java
  remoting/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/SofaRestRequestHandler.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/filter/PressureMarkTransformFilter.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/TripleServer.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/TripleTracerAdapter.java
  tools/pmd-ruleset.xml
  tracer/tracer-opentracing-resteasy/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/RestTracerAdapter.java
Labels: cla:yes, size/L

#1126 Fix/coverage
  .codecov.yml
  codecov.yml
Labels: bug, cla:yes, size/S

#1132 Callback mode supports default rejection policy adjustment
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcOptions.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/ConsumerConfig.java
  core/common/src/main/resources/com/alipay/sofa/rpc/common/rpc-config-default.json
  remoting/remoting-bolt/src/main/java/com/alipay/sofa/rpc/message/bolt/AbstractInvokeCallback.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/invoke/AsyncCallbackTest.java
Labels: cla:yes, size/L

#1135 Upgrade rpc 581
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/XS

#1137 Upgrade rpc version to 5.8.2-SNAPSHOT
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/S
