Repository sofastack/sofa-rpc, pull requests merged in 2021-07, with the labels that each got.

#1057 feat: try to obtain the unique service name from headerMap
  remoting/remoting-bolt/src/main/java/com/alipay/sofa/rpc/codec/bolt/SofaRpcSerialization.java
Labels: First-time contributor, cla:yes, size/S

#1058 upgrae version to 5.7.9
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/XS

#1054 fix custom header set
  core-impl/filter/src/main/java/com/alipay/sofa/rpc/filter/ConsumerCustomHeaderFilter.java
  core-impl/filter/src/test/java/com/alipay/sofa/rpc/filter/CustomHeaderFilterTest.java
  core/api/src/main/java/com/alipay/sofa/rpc/context/RpcInternalContext.java
  core/api/src/main/java/com/alipay/sofa/rpc/context/RpcInvokeContext.java
Labels: bug, cla:yes, size/M

#1064 fix #1056
  core/api/src/main/resources/sofa-rpc/logcodes-common_zh_CN.properties
Labels: First-time contributor, bug, cla:yes, size/XS
