Repository sofastack/sofa-rpc, pull requests merged in 2021-05, with the labels that each got.

#1039 Add the percentage of open issues and pull requests.
  README.md
Labels: cla:yes, size/XS

#1043 fix trace sample mark bug
  tracer/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/RpcSofaTracer.java
Labels: bug, cla:yes, size/M

#1044 Retry logic lose exeception bugfix
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/FailoverCluster.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/client/FailoverClusterTest.java
Labels: bug, cla:yes, size/M

#1045 update version to 5.7.8
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/XS, upgrade
