Repository sofastack/sofa-rpc, pull requests merged in 2021-01, with the labels that each got.

#1004 upgrade version to 5.7.7
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/S

#1013 fix remote id.
  extension-impl/remoting-resteasy/src/main/java/com/alipay/sofa/rpc/server/rest/SofaRestRequestHandler.java
  extension-impl/remoting-resteasy/src/test/java/com/alipay/sofa/rpc/server/rest/RemoteIpTest.java
Labels: bug, cla:yes, size/M

#1015 Use github action instead of travis
  .github/workflows/maven.yml
  README.md
  pom.xml
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/multi/MultiProtocolServerExpTest.java
Labels: cla:yes, size/M

#996 fix bug: compiler generate multi util method
  compiler/pom.xml
  compiler/src/main/resources/SofaTripleStub.mustache
Labels: bug, cla:yes, size/XS
