Repository sofastack/sofa-rpc, pull requests merged in 2021-09, with the labels that each got.

#1076 fix load props from header
  remoting/remoting-bolt/src/main/java/com/alipay/sofa/rpc/codec/bolt/SofaRpcSerialization.java
  remoting/remoting-bolt/src/test/java/com/alipay/sofa/rpc/codec/bolt/SimpleMapSerializerTest.java
Labels: cla:yes, size/L

#1063 Timeout priority bugfix
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/utils/StringUtils.java
  test/test-common/src/main/java/com/alipay/sofa/rpc/test/SampleService.java
  test/test-common/src/main/java/com/alipay/sofa/rpc/test/SampleServiceImpl.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/client/AbstractClusterTest.java
Labels: cla:yes, size/L

#1061 解决多线程本地变量丢失问题
  bom/pom.xml
  core/api/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/context/RpcInternalContext.java
  core/api/src/test/java/com/alipay/sofa/rpc/context/RpcInternalContextTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/triple/TripleHessianInvokeTest.java
Labels: cla:yes, First-time contributor, size/M

#1083 improve script
  .github/workflows/maven.yml
  .travis.yml
  registry/registry-nacos/src/test/scripts/start-nacos-server.sh
  registry/registry-nacos/src/test/scripts/stop-nacos-server.sh
  tools/change_version.sh
  tools/check_format.sh
Labels: cla:yes, First-time contributor, size/L

#1081 fix RpcInvokeContext not thread safe
  core/api/src/main/java/com/alipay/sofa/rpc/context/RpcInvokeContext.java
  core/api/src/test/java/com/alipay/sofa/rpc/context/RpcInvokeContextTest.java
  remoting/remoting-bolt/src/main/java/com/alipay/sofa/rpc/message/bolt/AbstractInvokeCallback.java
  remoting/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/http/AbstractHttpClientHandler.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/baggage/BAsyncChainSampleServiceImpl.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/baggage/BaggageAsyncChainTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/baggage/BaggageCallbackTest.java
Labels: bug, cla:yes, size/L

#1086 upgrade transmittable-thread-local to the most widely-used and recent stable version
  all/pom.xml
  bom/pom.xml
Labels: cla:yes, size/XS

#1090 Fix/load props from header
  remoting/remoting-bolt/src/main/java/com/alipay/sofa/rpc/codec/bolt/SofaRpcSerialization.java
  remoting/remoting-bolt/src/test/java/com/alipay/sofa/rpc/codec/bolt/SimpleMapSerializerTest.java
Labels: bug, cla:yes, size/M

#1093 fix cast exception in ProviderInfo getAttr method
  core/api/src/main/java/com/alipay/sofa/rpc/client/ProviderInfo.java
  core/api/src/test/java/com/alipay/sofa/rpc/client/ProviderInfoTest.java
Labels: bug, cla:yes, size/S

#1095 fix the qr code image link
  README.md
  README_zh_CN.md
Labels: bug, cla:yes, size/XS

#1106 Generic invoke using custom serialization & triple generic invoke
  codec/codec-jackson/src/main/java/com/alipay/sofa/rpc/codec/jackson/JacksonHelper.java
  codec/codec-jackson/src/main/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializer.java
  codec/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializerTest.java
  example/pom.xml
  example/src/test/java/com/alipay/sofa/rpc/invoke/genericJson/GenericJsonTest.java
  example/src/test/java/com/alipay/sofa/rpc/invoke/genericJson/IGenericService.java
  example/src/test/java/com/alipay/sofa/rpc/invoke/genericJson/IGenericServiceImpl.java
  example/src/test/java/com/alipay/sofa/rpc/invoke/genericJson/TestEntity.java
  remoting/remoting-http/pom.xml
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/transport/triple/TripleClientInvoker.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/tripleGeneric/TestEntity.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/tripleGeneric/TripleGenericInterface.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/tripleGeneric/TripleGenericInterfaceImpl.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/tripleGeneric/TripleGenericTest.java
Labels: cla:yes, First-time contributor, size/XL
