Repository sofastack/sofa-rpc, pull requests merged in 2022-10, with the labels that each got.

#1211 Bump netty from 4.1.44.Final to 4.1.77.Final
  bom/pom.xml
Labels: cla:yes, First-time contributor, size/XS

#1259 Feature/add rpc generic throw exception
  codec/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/GenericMultipleClassLoaderSofaSerializerFactory.java
  codec/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/GenericSingleClassLoaderSofaSerializerFactory.java
  codec/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SingleClassLoaderSofaSerializerFactory.java
  codec/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/serialize/GenericCustomThrowableDeterminer.java
  codec/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/serialize/SofaResponseHessianSerializer.java
  codec/codec-sofa-hessian/src/test/java/com/alipay/sofa/rpc/codec/sofahessian/GenericMultipleClassLoaderSofaSerializerFactoryTest.java
  codec/codec-sofa-hessian/src/test/java/com/alipay/sofa/rpc/codec/sofahessian/GenericSingleClassLoaderSofaSerializerFactoryTest.java
  codec/codec-sofa-hessian/src/test/java/com/alipay/sofa/rpc/codec/sofahessian/mock/MockError.java
  codec/codec-sofa-hessian/src/test/java/com/alipay/sofa/rpc/codec/sofahessian/serialize/GenericCustomThrowableDeterminerTest.java
  codec/codec-sofa-hessian/src/test/java/com/alipay/sofa/rpc/codec/sofahessian/serialize/SofaResponseHessianSerializerTest.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/config/RpcConfigKeys.java
Labels: cla:yes, First-time contributor, size/L

#1264 support json encode null and isError
  codec/codec-jackson/src/main/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializer.java
  codec/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializerTest.java
Labels: cla:yes, First-time contributor, size/M

#1257 fix DoaminRegistry multi inited
  registry/registry-local/src/main/java/com/alipay/sofa/rpc/registry/local/DomainRegistry.java
  registry/registry-local/src/test/java/com/alipay/sofa/rpc/registry/local/DomainRegistryTest.java
Labels: bug, cla:yes, size/M

#1250 LogCodes-Spelling mistake(ERROR_NO_AVAILBLE_PROVIDER->ERROR_NO_AVAILA…
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractLoadBalancer.java
  core/api/src/main/java/com/alipay/sofa/rpc/log/LogCodes.java
Labels: cla:yes, size/XS

#1266 Improve/list diference
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AllConnectConnectionHolder.java
  core/api/src/test/java/com/alipay/sofa/rpc/bench/CollectionDifferenceBenchMarkTest.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/struct/SetDifference.java
  core/common/src/test/java/com/alipay/sofa/rpc/common/struct/SetDifferenceTest.java
  pom.xml
Labels: cla:yes, size/L

#1269 fix domainRegistry init problem
  registry/registry-local/src/main/java/com/alipay/sofa/rpc/registry/local/DomainRegistry.java
  registry/registry-local/src/test/java/com/alipay/sofa/rpc/registry/local/DomainRegistryTest.java
Labels: bug, cla:yes, size/M

#1271 upgrade rpc version to 5.8.8
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/S
