Repository sofastack/sofa-rpc, pull requests merged in 2022-11, with the labels that each got.

#1275 rpc unique id character check support disable
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcOptions.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/AbstractInterfaceConfig.java
  core/api/src/test/java/com/alipay/sofa/rpc/std/config/AbstractInterfaceConfigTest.java
  core/common/src/main/resources/com/alipay/sofa/rpc/common/rpc-config-default.json
Labels: cla:yes, size/M

#1272 correct the comment for isRandomPort(). (#1256)
  core/api/src/main/java/com/alipay/sofa/rpc/common/utils/NetUtils.java
Labels: cla:yes, First-time contributor, size/XS

#1276 optimize comment of package-info.java. (#1273)
  core/api/src/main/java/com/alipay/sofa/rpc/bootstrap/package-info.java
  core/api/src/main/java/com/alipay/sofa/rpc/client/package-info.java
  core/api/src/main/java/com/alipay/sofa/rpc/codec/package-info.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/json/package-info.java
  fault/fault-tolerance/src/main/java/com/alipay/sofa/rpc/client/aft/package-info.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/exception/package-info.java
Labels: cla:yes, First-time contributor, size/M

#1249 triple invoke support callback&future
  all/pom.xml
  bom/pom.xml
  example/pom.xml
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/message/triple/TripleResponseFuture.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/transport/triple/TripleClientInvoker.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/transport/triple/TripleClientTransport.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/transport/triple/TripleInvoker.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/baggage/BaggageOnewayTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/triple/TripleAsyncInvokeTest.java
Labels: cla:yes, size/L

#1277 upgrade rpc to 5.9.0
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/XS
