Repository sofastack/sofa-rpc, pull requests merged in 2022-09, with the labels that each got.

#1238 Add github action to release jar
  .github/workflows/release.yml
  all/pom.xml
Labels: cla:yes, size/M

#1241 improve efficiency of list difference
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AllConnectConnectionHolder.java
  core/api/src/test/java/com/alipay/sofa/rpc/bench/CollectionDifferenceBenchMarkTest.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/struct/SetDifference.java
  core/common/src/test/java/com/alipay/sofa/rpc/common/struct/SetDifferenceTest.java
  pom.xml
Labels: cla:yes, First-time contributor, size/L

#1243 Fix log connection get error
  remoting/remoting-bolt/src/main/java/com/alipay/sofa/rpc/transport/bolt/ReuseBoltClientConnectionManager.java
Labels: bug, cla:yes, size/XS

#1237 upgrade rpc version to 5.9.0-SNAPSHOT
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/S

#1242 feat: add more parameters to nacosConfig, then you can pass usr/pwd p…
  registry/registry-nacos/src/main/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistry.java
Labels: question, cla:no, First-time contributor, size/XS

#1231 add proxy bench mark
  core-impl/proxy/src/main/java/com/alipay/sofa/rpc/proxy/bytebuddy/BytebuddyProxy.java
  core-impl/proxy/src/main/java/com/alipay/sofa/rpc/proxy/javassist/JavassistProxy.java
  core-impl/proxy/src/test/java/com/alipay/sofa/rpc/proxy/ProxyBuildBenchMark.java
  core-impl/proxy/src/test/java/com/alipay/sofa/rpc/proxy/ProxyInvokeBenchMark.java
Labels: cla:yes, size/L
