Repository sofastack/sofa-rpc, pull requests merged in 2022-02, with the labels that each got.

#1165 Rename stale settings name
  .github/stale.yml
Labels: cla:yes, size/XS

#1161 add method: getUserThreadPoolMap
  core/api/src/main/java/com/alipay/sofa/rpc/config/UserThreadPoolManager.java
  core/api/src/main/java/com/alipay/sofa/rpc/server/UserThreadPool.java
  core/api/src/test/java/com/alipay/sofa/rpc/config/UserThreadPoolManagerTest.java
Labels: cla:yes, size/M

#1006 modify triple unique id logic
  bootstrap/bootstrap-triple/src/main/java/com/alipay/sofa/rpc/bootstrap/triple/TripleProviderBootstrap.java
  example/pom.xml
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/constant/TripleConstant.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/TripleContants.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/TripleServer.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/UniqueIdInvoker.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/TripleTracerAdapter.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/transport/triple/TripleClientInvoker.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/utils/SofaProtoUtils.java
  remoting/remoting-triple/src/test/java/com/alipay/sofa/rpc/server/triple/UniqueIdInvokerTest.java
  test/test-integration/pom.xml
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/triple/TripleServerTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/triple/TripleHessianInvokeTest.java
Labels: cla:yes, First-time contributor, size/XL

#1164 fix-destroy方法的错误代码
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
  core-impl/client/src/test/java/com/alipay/sofa/rpc/client/AbstractClusterTest.java
Labels: bug, cla:yes, First-time contributor, size/M

#1166 remove unused triple proxy
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/GenericServiceImpl.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/TripleServer.java
  remoting/remoting-triple/src/test/java/com/alipay/sofa/rpc/server/triple/GenericServiceImplTest.java
Labels: cla:yes, size/M

#1167 remove RpcInvokeContext when triple invoke completed
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/interceptor/ServerReqHeaderInterceptor.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/TripleTracerAdapter.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/triple/TripleHessianInterface.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/triple/TripleHessianInterfaceImpl.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/triple/TripleHessianInvokeTest.java
Labels: question, cla:yes, size/L

#1173 Optimization with StringBuilder #1170
  core/api/src/main/java/com/alipay/sofa/rpc/protocol/telnet/HelpTelnetHandler.java
Labels: cla:yes, First-time contributor, size/XS
