Repository sofastack/sofa-rpc, pull requests merged in 2022-01, with the labels that each got.

#1154 upgrade rpc version to 5.8.2
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/XS

#1155 upgrade rpc version to 5.8.3-SNAPSHOT
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/S

#1152 Feat/add log
  remoting/remoting-bolt/src/main/java/com/alipay/sofa/rpc/codec/bolt/SofaRpcSerialization.java
  remoting/remoting-bolt/src/test/java/com/alipay/sofa/rpc/codec/bolt/SofaRpcSerializationTest.java
Labels: cla:yes, size/L
