Repository sofastack/sofa-rpc, pull requests merged in 2022-04, with the labels that each got.

#1190 sub unSub and unRegister request add ProtocolType
  registry/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/MeshRegistry.java
  registry/registry-mesh/src/test/java/com/alipay/sofa/rpc/registry/mesh/MeshRegistryTest.java
Labels: cla:yes, size/M

#1192 add exemptLabels for stale bot
  .github/stale.yml
Labels: cla:yes, size/XS

#1193 fix: generic interface deserialize error by json
  bootstrap/bootstrap-api/src/main/java/com/alipay/sofa/rpc/bootstrap/DefaultProviderBootstrap.java
  codec/codec-jackson/src/main/java/com/alipay/sofa/rpc/codec/jackson/JacksonHelper.java
  codec/codec-jackson/src/main/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializer.java
  codec/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializerTest.java
  codec/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/generic/GenericService.java
  codec/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/generic/GenericServiceImpl.java
  codec/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/generic/MyReq.java
  codec/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/generic/MyResp.java
  core/api/src/main/java/com/alipay/sofa/rpc/codec/AbstractSerializer.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/RemotingConstants.java
Labels: bug, cla:yes, First-time contributor, size/L

#1196 Upgrade rpc 584
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/XS
