Repository sofastack/sofa-rpc, pull requests merged in 2022-03, with the labels that each got.

#1177 upgrade rpc version to 5.8.3
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/XS

#1178 upgrade rpc version to 5.8.4-SNAPSHOT
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/S

#1147 Registry polaris
  all/pom.xml
  bom/pom.xml
  example/pom.xml
  example/src/test/java/com/alipay/sofa/rpc/polaris/PolarisBoltClientMain.java
  example/src/test/java/com/alipay/sofa/rpc/polaris/PolarisBoltServerMain.java
  registry/pom.xml
  registry/registry-polaris/pom.xml
  registry/registry-polaris/src/main/java/com/alipay/sofa/rpc/registry/polaris/PolarisConstants.java
  registry/registry-polaris/src/main/java/com/alipay/sofa/rpc/registry/polaris/PolarisRegistry.java
  registry/registry-polaris/src/main/java/com/alipay/sofa/rpc/registry/polaris/PolarisRegistryProperties.java
  registry/registry-polaris/src/main/java/com/alipay/sofa/rpc/registry/polaris/PolarisWatcher.java
  registry/registry-polaris/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.registry.Registry
  registry/registry-polaris/src/test/java/com/alipay/sofa/rpc/registry/polaris/PolarisRegistryTest.java
  registry/registry-polaris/src/test/resources/log4j.xml
  registry/registry-polaris/src/test/resources/sofa-rpc/rpc-config.json
Labels: cla:yes, First-time contributor, size/XXL

#1179 fix multiple subscribe error
  registry/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/ConsulRegistry.java
  registry/registry-polaris/src/main/java/com/alipay/sofa/rpc/registry/polaris/PolarisRegistry.java
Labels: bug, cla:yes, size/S

#1169 feat: consul registry support acl(#1168)
  registry/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/ConsulConstants.java
  registry/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/ConsulRegistry.java
  registry/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/ConsulRegistryProperties.java
  registry/registry-consul/src/main/java/com/alipay/sofa/rpc/registry/consul/HealthServiceInformer.java
  registry/registry-consul/src/test/java/com/alipay/sofa/rpc/registry/consul/ConsulRegistryAclTest.java
Labels: cla:yes, First-time contributor, size/L

#1181 Update arch png
  README.md
  README_zh_CN.md
  resource/sofa-rpc-architecture.png
Labels: cla:yes, size/XS

#1163 Ut/bootstrap api
  bom/pom.xml
  core/api/src/test/java/com/alipay/sofa/rpc/client/ProviderInfoTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/log/TimeWaitLoggerTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/std/AbstractMockitoTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/std/config/AbstractIdConfigTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/std/config/AbstractInterfaceConfigTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/std/config/ConfigUniqueNameGeneratorTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/std/config/ConsumerConfigTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/std/config/ProviderConfigTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/std/sample/SampleService.java
  core/api/src/test/java/com/alipay/sofa/rpc/std/sample/SampleServiceImpl.java
  core/api/src/test/java/com/alipay/sofa/rpc/transport/ClientTransportFactoryTest.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/utils/TestUtils.java
  core/common/src/test/java/com/alipay/sofa/rpc/common/utils/TestUtilsTest.java
  pom.xml
Labels: cla:yes, size/XL
