Repository sofastack/sofa-rpc, pull requests merged in 2023-09, with the labels that each got.

#1366 upgrade rpc version to 5.11.1-SNAPSHOT
  all/pom.xml
  bom/pom.xml
  codec/codec-sofa-hessian/src/main/resources/sofa-rpc/serialize_blacklist.txt
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/S

#1367 release 5.11.1
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/XS

#1370 doc: add ant codespaces badge
  README.md
  README_zh_CN.md
Labels: cla:no, cla:yes, First-time contributor, size/XS
