Repository sofastack/sofa-rpc, pull requests merged in 2023-08, with the labels that each got.

#1303 Fix mac aarch compilation
  .gitignore
  all/pom.xml
  bom/pom.xml
  example/pom.xml
  pom.xml
  registry/registry-nacos/pom.xml
  registry/registry-nacos/src/test/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistryTest.java
  registry/registry-nacos/src/test/java/com/alipay/sofa/rpc/registry/nacos/base/BaseNacosTest.java
  registry/registry-sofa/pom.xml
  registry/registry-sofa/src/test/java/com/alipay/sofa/common/profile/StringUtil.java
  remoting/remoting-triple/build/generated/source/proto/main/java/triple/GenericProto.java
  remoting/remoting-triple/build/generated/source/proto/main/java/triple/GenericServiceGrpc.java
  remoting/remoting-triple/build/generated/source/proto/main/java/triple/Request.java
  remoting/remoting-triple/build/generated/source/proto/main/java/triple/RequestOrBuilder.java
  remoting/remoting-triple/build/generated/source/proto/main/java/triple/Response.java
  remoting/remoting-triple/build/generated/source/proto/main/java/triple/ResponseOrBuilder.java
  test/test-integration/pom.xml
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/triple/TripleServerTest.java
  tracer/tracer-opentracing/pom.xml
Labels: bug, cla:yes, size/XL

#1357 1,代码扫描流程忽略dependabot的提交
  .github/workflows/cloud_code_scan.yml
Labels: cla:yes, size/XS

#1359 code-scan support opensource check
  .github/workflows/cloud_code_scan.yml
Labels: cla:yes, size/XS

#1361 fix directUrl transform exception
  registry/registry-local/src/main/java/com/alipay/sofa/rpc/registry/local/DomainRegistry.java
Labels: bug, cla:yes, size/XS

#1356 Sofaboot 4.0 support
  all/pom.xml
  bom/pom.xml
  bootstrap/bootstrap-dubbo/pom.xml
  bootstrap/bootstrap-dubbo/src/main/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubboConsumerBootstrap.java
  bootstrap/bootstrap-dubbo/src/main/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubboConvertor.java
  bootstrap/bootstrap-dubbo/src/main/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubboProviderBootstrap.java
  bootstrap/bootstrap-dubbo/src/main/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubboSingleton.java
  bootstrap/bootstrap-dubbo/src/test/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubooServerTest.java
  bootstrap/bootstrap-triple/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  example/pom.xml
  example/src/test/java/com/alipay/sofa/rpc/zookeeper/start/ZookeeperBoltClientMain.java
  example/src/test/java/com/alipay/sofa/rpc/zookeeper/start/ZookeeperBoltServerMain.java
  log-common-tools/src/main/java/com/alipay/sofa/rpc/log/factory/RpcLoggerFactory.java
  pom.xml
  registry/registry-zk/pom.xml
  test/test-integration-3rd/pom.xml
  test/test-integration-3rd/src/test/java/com/alipay/sofa/rpc/bootstrap/dubbo/DubboServerTest.java
Labels: cla:yes, size/L
