Repository sofastack/sofa-rpc, pull requests merged in 2023-02, with the labels that each got.

#1312 Fix serialize test
  codec/codec-sofa-hessian/src/test/java/com/alipay/sofa/rpc/codec/sofahessian/serialize/SofaResponseHessianSerializerTest.java
Labels: bug, cla:yes, size/XS

#1307 Upgrade rpc 592
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/S

#1306 Fix#1254#1305 bug on JSON serialization and deserialization
  core/common/src/main/java/com/alipay/sofa/rpc/common/json/BeanSerializer.java
  core/common/src/test/java/com/alipay/sofa/rpc/common/json/JSONTest.java
  core/common/src/test/java/com/alipay/sofa/rpc/common/json/TestJsonBean.java
Labels: bug, cla:yes, First-time contributor, size/M
