Repository sofastack/sofa-rpc, pull requests merged in 2023-07, with the labels that each got.

#1352 小程序云代码扫描
  .github/workflows/cloud_code_scan.yml
Labels: cla:yes, size/S

#1353 代码扫描fix
  .github/workflows/cloud_code_scan.yml
Labels: cla:yes, size/XS

#1351 upgrade rpc version to 5.11.0-SNAPSHOT
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/S

#1354 update security
  SECURITY.md
  codec/codec-sofa-hessian/src/main/resources/sofa-rpc/serialize_blacklist.txt
Labels: cla:yes, size/S

#1355 fix unit test unstable problem
  registry/registry-mesh/src/test/java/com/alipay/sofa/rpc/registry/mesh/MeshApiClientTest.java
  registry/registry-mesh/src/test/java/com/alipay/sofa/rpc/registry/mesh/MeshRegistryTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/baggage/BaggageAsyncChainTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/baggage/BaggageCallbackTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/baggage/BaggageFutureTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/baggage/BaggageOnewayTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/baggage/BaggageSyncTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/baggage/BoltProtobufBaggageSyncTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/triple/TripleHessianInvokeTest.java
Labels: bug, cla:yes, size/M
