Repository sofastack/sofa-rpc, pull requests merged in 2023-01, with the labels that each got.

#1291 fix unit test
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/triple/TripleAsyncInvokeTest.java
Labels: bug, cla:yes, size/XS

#1288 fix getDeserializerForCustomThrowable performance
  codec/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/GenericMultipleClassLoaderSofaSerializerFactory.java
  codec/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/GenericSingleClassLoaderSofaSerializerFactory.java
  codec/codec-sofa-hessian/src/test/java/com/alipay/sofa/rpc/codec/sofahessian/GenericMultipleClassLoaderSofaSerializerFactoryTest.java
  codec/codec-sofa-hessian/src/test/java/com/alipay/sofa/rpc/codec/sofahessian/GenericSingleClassLoaderSofaSerializerFactoryTest.java
  codec/codec-sofa-hessian/src/test/java/com/alipay/sofa/rpc/codec/sofahessian/serialize/GenericCustomThrowableDeterminerTest.java
  codec/codec-sofa-hessian/src/test/java/com/alipay/sofa/rpc/codec/sofahessian/serialize/SofaResponseHessianSerializerTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/test/generic/GenericBenchmarkTest.java
Labels: bug, cla:yes, size/L

#1280 support prometheus
  all/pom.xml
  bom/pom.xml
  metrics/metrics-prometheus/pom.xml
  metrics/metrics-prometheus/src/main/java/com/alipay/sofa/rpc/metrics/prometheus/MetricsBuilder.java
  metrics/metrics-prometheus/src/main/java/com/alipay/sofa/rpc/metrics/prometheus/SofaRpcMetricsCollector.java
  metrics/metrics-prometheus/src/test/java/com/alipay/sofa/rpc/metrics/prometheus/SofaRpcMetricsCollectorTest.java
  metrics/pom.xml
Labels: cla:yes, First-time contributor, size/XL

#1289 Fix the problem of triple header losing information
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/TripleTracerAdapter.java
  remoting/remoting-triple/src/test/java/com/alipay/sofa/rpc/tracer/sofatracer/TripleTracerAdapterTest.java
Labels: bug, cla:yes, size/M

#1294 upgrade rpc version to 5.9.1
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/XS
