Repository sofastack/sofa-rpc, pull requests merged in 2024-08, with the labels that each got.

#1433 fix: remove wrong verify logic
  remoting/remoting-http/src/test/java/com/alipay/sofa/rpc/transport/netty/NettyBatchWriteQueueTest.java
  remoting/remoting-http/src/test/java/com/alipay/sofa/rpc/transport/netty/NettyChannelTest.java
Labels: bug, cla:yes, size/S

#1438 Jackson serialization for multi classloader
  codec/codec-jackson/src/main/java/com/alipay/sofa/rpc/codec/jackson/JacksonHelper.java
  codec/codec-jackson/src/main/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializer.java
Labels: cla:yes, First-time contributor, size/M

#1436 enhance log format
  core/api/src/main/java/com/alipay/sofa/rpc/log/LogCodes.java
Labels: cla:yes, size/XS

#1437 update rpc to 5.13.1
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/XS

#1439 update hessian and tracer version
  all/pom.xml
  bom/pom.xml
Labels: cla:yes, size/XS
