Repository sofastack/sofa-rpc, pull requests merged in 2024-05, with the labels that each got.

#1402 fix baggage do not pick up to RpcInvokeContext problem
  remoting/remoting-bolt/src/main/java/com/alipay/sofa/rpc/codec/bolt/SofaRpcSerialization.java
  remoting/remoting-bolt/src/test/java/com/alipay/sofa/rpc/codec/bolt/SofaRpcSerializationTest.java
  remoting/remoting-bolt/src/test/resources/sofa-rpc/rpc-config.json
Labels: bug, cla:yes, size/S

#1399 Support bzip2 and gzip compress
  all/pom.xml
  bom/pom.xml
  codec/codec-api/pom.xml
  codec/codec-api/src/main/java/com/alipay/sofa/rpc/codec/bzip2/Bzip2RpcCompressor.java
  codec/codec-api/src/main/java/com/alipay/sofa/rpc/codec/gzip/GzipRpcCompressor.java
  codec/codec-api/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.codec.Compressor
  codec/codec-api/src/test/java/com/alipay/sofa/rpc/codec/bzip2/Bzip2RpcCompressorTest.java
  codec/codec-api/src/test/java/com/alipay/sofa/rpc/codec/gzip/GzipRpcCompressorTest.java
Labels: cla:yes, size/L

#1400 Optimize performance for h2c protocol
  core/common/src/main/java/com/alipay/sofa/rpc/common/BatchExecutorQueue.java
  core/common/src/test/java/com/alipay/sofa/rpc/common/BatchExecutorQueueTest.java
  remoting/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/netty/NettyBatchWriteQueue.java
  remoting/remoting-http/src/main/java/com/alipay/sofa/rpc/transport/netty/NettyChannel.java
  remoting/remoting-http/src/test/java/com/alipay/sofa/rpc/transport/netty/NettyBatchWriteQueueTest.java
  remoting/remoting-http/src/test/java/com/alipay/sofa/rpc/transport/netty/NettyChannelTest.java
Labels: cla:yes, size/L, later

#1415 support default filter config
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcOptions.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/AbstractInterfaceConfig.java
  core/api/src/test/java/com/alipay/sofa/rpc/filter/FilterChainTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/std/config/AbstractInterfaceConfigTest.java
  core/api/src/test/resources/sofa-rpc/rpc-config.json
  core/common/src/main/resources/com/alipay/sofa/rpc/common/rpc-config-default.json
Labels: cla:yes, size/M

#1416 support consumer routers config
  core/api/src/main/java/com/alipay/sofa/rpc/client/RouterChain.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcOptions.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/ConsumerConfig.java
  core/api/src/main/java/com/alipay/sofa/rpc/filter/FilterChain.java
  core/api/src/test/java/com/alipay/sofa/rpc/client/RouterChainTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/std/config/ConsumerConfigTest.java
  core/api/src/test/resources/sofa-rpc/rpc-config.json
  core/common/src/main/resources/com/alipay/sofa/rpc/common/rpc-config-default.json
Labels: cla:yes, size/M

#1420 upgrade rpc version to 5.13.0
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/XS
