Repository sofastack/sofa-rpc, pull requests merged in 2024-10, with the labels that each got.

#1447 Remove lookout
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcOptions.java
  metrics/metrics-lookout/pom.xml
  metrics/metrics-lookout/src/main/java/com/alipay/sofa/rpc/event/LookoutSubscriber.java
  metrics/metrics-lookout/src/main/java/com/alipay/sofa/rpc/metrics/lookout/RpcAbstractLookoutModel.java
  metrics/metrics-lookout/src/main/java/com/alipay/sofa/rpc/metrics/lookout/RpcClientLookoutModel.java
  metrics/metrics-lookout/src/main/java/com/alipay/sofa/rpc/metrics/lookout/RpcLookout.java
  metrics/metrics-lookout/src/main/java/com/alipay/sofa/rpc/metrics/lookout/RpcLookoutId.java
  metrics/metrics-lookout/src/main/java/com/alipay/sofa/rpc/metrics/lookout/RpcServerLookoutModel.java
  metrics/metrics-lookout/src/main/java/com/alipay/sofa/rpc/module/LookoutModule.java
  metrics/metrics-lookout/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.module.Module
  metrics/metrics-lookout/src/test/java/com/alipay/sofa/rpc/module/ConsumerSubTest.java
  metrics/metrics-lookout/src/test/java/com/alipay/sofa/rpc/module/LookoutModuleTest.java
  metrics/metrics-lookout/src/test/java/com/alipay/sofa/rpc/module/ProviderPubTest.java
  metrics/pom.xml
  registry/registry-sofa/pom.xml
  test/test-integration/pom.xml
  test/test-integration/src/test/java/com/alipay/sofa/rpc/metrics/lookout/LookoutService.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/metrics/lookout/LookoutServiceImpl.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/metrics/lookout/RpcLookoutTest.java
  test/test-integration/src/test/java/com/alipay/sofa/rpc/server/rest/RestLookoutTest.java
Labels: cla:yes, size/XXL

#1432 feat: support triple grpc heart beat
  core/api/src/main/java/com/alipay/sofa/rpc/common/RpcOptions.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/config/RpcConfigKeys.java
  core/common/src/main/resources/com/alipay/sofa/rpc/common/rpc-config-default.json
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/transport/triple/TripleClientTransport.java
  remoting/remoting-triple/src/test/java/com/alipay/sofa/rpc/transport/triple/TripleClientTransportTest.java
Labels: cla:yes, size/L

#1440 fix organization url, the http://www.antfin.com is currently unavailable
  all/pom.xml
  pom.xml
Labels: bug, cla:yes, size/S

#1453 enhance code
  codec/codec-api/src/main/resources/sofa-rpc/serialize_blacklist.txt
Labels: cla:yes, size/S

#1450 add SofaRejectedExecutionHandler for user-customized thread pool
  core/api/src/main/java/com/alipay/sofa/rpc/server/UserThreadPool.java
  core/api/src/test/java/com/alipay/sofa/rpc/config/UserThreadPoolManagerTest.java
Labels: cla:yes, First-time contributor, size/S

#1452 fix: update provider to null
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AbstractCluster.java
  core-impl/client/src/test/java/com/alipay/sofa/rpc/client/ClusterProviderUpdateTest.java
Labels: bug, cla:yes, size/L

#1454 Mesh Registry support custom group for sofa registry.
  registry/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/MeshRegistry.java
  registry/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/PublishServiceRequest.java
  registry/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/SubscribeServiceRequest.java
  registry/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/UnPublishServiceRequest.java
  registry/registry-mesh/src/main/java/com/alipay/sofa/rpc/registry/mesh/model/UnSubscribeServiceRequest.java
  registry/registry-mesh/src/test/java/com/alipay/sofa/rpc/registry/mesh/MeshRegistryTest.java
Labels: cla:yes, size/L

#1455 release rpc version 5.13.2
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/XS
