Repository sofastack/sofa-rpc, pull requests merged in 2024-01, with the labels that each got.

#1348 add fury serializer
  all/pom.xml
  bom/pom.xml
  codec/codec-api/src/main/java/com/alipay/sofa/rpc/codec/common/BlackAndWhiteListFileLoader.java
  codec/codec-api/src/main/java/com/alipay/sofa/rpc/codec/common/SerializeCheckStatus.java
  codec/codec-api/src/main/resources/sofa-rpc/serialize_blacklist.txt
  codec/codec-sofa-fury/pom.xml
  codec/codec-sofa-fury/src/main/java/com/alipay/sofa/rpc/codec/fury/FurySerializer.java
  codec/codec-sofa-fury/src/main/java/com/alipay/sofa/rpc/codec/fury/serialize/SofaRequestFurySerializer.java
  codec/codec-sofa-fury/src/main/java/com/alipay/sofa/rpc/codec/fury/serialize/SofaResponseFurySerializer.java
  codec/codec-sofa-fury/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.codec.Serializer
  codec/codec-sofa-fury/src/test/java/com/alipay/sofa/rpc/codec/fury/FurySerializerTest.java
  codec/codec-sofa-fury/src/test/java/com/alipay/sofa/rpc/codec/fury/model/blacklist/BlackListClass.java
  codec/codec-sofa-fury/src/test/java/com/alipay/sofa/rpc/codec/fury/model/none/NoneClassHasBlackClass.java
  codec/codec-sofa-fury/src/test/java/com/alipay/sofa/rpc/codec/fury/model/whitelist/DemoRequest.java
  codec/codec-sofa-fury/src/test/java/com/alipay/sofa/rpc/codec/fury/model/whitelist/DemoResponse.java
  codec/codec-sofa-fury/src/test/java/com/alipay/sofa/rpc/codec/fury/model/whitelist/DemoService.java
  codec/codec-sofa-fury/src/test/java/com/alipay/sofa/rpc/codec/fury/model/whitelist/WhiteClassHasBlackClass.java
  codec/codec-sofa-fury/src/test/resources/log4j.xml
  codec/codec-sofa-fury/src/test/resources/sofa-rpc/rpc-config.json
  codec/codec-sofa-fury/src/test/resources/sofa-rpc/serialize_blacklist.txt
  codec/codec-sofa-fury/src/test/resources/sofa-rpc/serialize_whitelist.txt
  codec/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SofaHessianSerializer.java
  codec/codec-sofa-hessian/src/test/java/com/alipay/sofa/rpc/codec/sofahessian/BlackAndWhiteListFileLoaderTest.java
  codec/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/codec/AbstractSerializer.java
  core/api/src/main/java/com/alipay/sofa/rpc/codec/CustomSerializer.java
  core/api/src/main/java/com/alipay/sofa/rpc/ext/ExtensionLoader.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/SofaOptions.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/config/RpcConfigKeys.java
  core/common/src/main/resources/com/alipay/sofa/rpc/common/rpc-config-default.json
Labels: cla:yes, size/XXL, later

#1385 bump hessian to 3.5.2
  all/pom.xml
  bom/pom.xml
Labels: cla:yes, size/XS

#1358 1,修复gson版本导致的漏洞
  config/config-apollo/pom.xml
Labels: cla:yes, size/XS

#1383 Feat/threadpool ext
  all/pom.xml
  bom/pom.xml
  core-impl/client/src/main/java/com/alipay/sofa/rpc/client/AllConnectConnectionHolder.java
  core-impl/filter/src/main/java/com/alipay/sofa/rpc/filter/BeanIdMatchFilter.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/threadpool/SofaExecutorFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/threadpool/ThreadPoolConstant.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/threadpool/extension/CachedThreadPoolFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/threadpool/extension/VirtualThreadPoolFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/config/ServerConfig.java
  core/api/src/main/java/com/alipay/sofa/rpc/dynamic/DynamicConfigManagerFactory.java
  core/api/src/main/java/com/alipay/sofa/rpc/server/BusinessPool.java
  core/api/src/main/java/com/alipay/sofa/rpc/server/UserThreadPool.java
  core/api/src/main/java/com/alipay/sofa/rpc/server/UserVirtualThreadPool.java
  core/api/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.common.threadpool.SofaExecutorFactory
  core/api/src/test/java/com/alipay/sofa/rpc/common/threadpool/ExecutorFactoryTest.java
  core/api/src/test/java/com/alipay/sofa/rpc/config/UserThreadPoolManagerTest.java
  core/common/src/main/java/com/alipay/sofa/rpc/common/config/RpcConfigKeys.java
  metrics/metrics-lookout/src/main/java/com/alipay/sofa/rpc/event/LookoutSubscriber.java
  metrics/metrics-lookout/src/main/java/com/alipay/sofa/rpc/metrics/lookout/RpcLookoutId.java
  remoting/remoting-bolt/src/main/java/com/alipay/sofa/rpc/server/bolt/BoltServer.java
  remoting/remoting-bolt/src/main/java/com/alipay/sofa/rpc/server/bolt/BoltServerProcessor.java
  remoting/remoting-bolt/src/test/java/com/alipay/sofa/rpc/server/bolt/BoltServerTest.java
Labels: cla:yes, size/XL

#1387 add dep fury
  all/pom.xml
  codec/codec-sofa-fury/src/main/java/com/alipay/sofa/rpc/codec/fury/FurySerializer.java
  codec/codec-sofa-fury/src/main/java/com/alipay/sofa/rpc/codec/fury/serialize/SofaRequestFurySerializer.java
  codec/codec-sofa-fury/src/main/java/com/alipay/sofa/rpc/codec/fury/serialize/SofaResponseFurySerializer.java
  core/api/src/main/java/com/alipay/sofa/rpc/codec/AbstractSerializer.java
Labels: cla:yes, size/M

#1388 feat: support jackson config
  codec/codec-jackson/src/main/java/com/alipay/sofa/rpc/codec/jackson/JacksonConfigKeys.java
  codec/codec-jackson/src/main/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializer.java
  codec/codec-jackson/src/test/java/com/alipay/sofa/rpc/codec/jackson/JacksonSerializerTest.java
Labels: cla:yes, size/L

#1393 chore: virtual thread name
  core/api/src/main/java/com/alipay/sofa/rpc/common/threadpool/ThreadPoolConstant.java
  core/api/src/main/java/com/alipay/sofa/rpc/common/threadpool/extension/VirtualThreadPoolFactory.java
Labels: cla:yes, size/M

#1394 release 5.12.0
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/S
