Repository sofastack/sofa-rpc, pull requests merged in 2024-03, with the labels that each got.

#1401 fix #1380, create NacosRegistryProviderObserver when init method is executed
  registry/registry-nacos/src/main/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistry.java
  registry/registry-nacos/src/test/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistryTest.java
Labels: bug, question, cla:yes, size/M

#1395 Extension kubernetes registry
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/config/RegistryConfig.java
  registry/pom.xml
  registry/registry-kubernetes/pom.xml
  registry/registry-kubernetes/src/main/java/com/alipay/sofa/rpc/registry/kubernetes/KubernetesRegistry.java
  registry/registry-kubernetes/src/main/java/com/alipay/sofa/rpc/registry/kubernetes/KubernetesRegistryHelper.java
  registry/registry-kubernetes/src/main/java/com/alipay/sofa/rpc/registry/kubernetes/KubernetesRegistryProviderWatcher.java
  registry/registry-kubernetes/src/main/java/com/alipay/sofa/rpc/registry/kubernetes/constant/KubernetesClientConstants.java
  registry/registry-kubernetes/src/main/java/com/alipay/sofa/rpc/registry/kubernetes/utils/KubernetesClientUtils.java
  registry/registry-kubernetes/src/main/java/com/alipay/sofa/rpc/registry/kubernetes/utils/KubernetesConfigUtils.java
  registry/registry-kubernetes/src/main/resources/META-INF/services/sofa-rpc/com.alipay.sofa.rpc.registry.Registry
  registry/registry-kubernetes/src/test/java/com/alipay/sofa/rpc/registry/kubernetes/KubernetesRegistryTest.java
  registry/registry-kubernetes/src/test/java/com/alipay/sofa/rpc/registry/kubernetes/TestService.java
  registry/registry-kubernetes/src/test/java/com/alipay/sofa/rpc/registry/kubernetes/TestService2.java
  registry/registry-kubernetes/src/test/java/com/alipay/sofa/rpc/registry/kubernetes/TestServiceImpl.java
  registry/registry-kubernetes/src/test/java/com/alipay/sofa/rpc/registry/kubernetes/TestServiceImpl2.java
  registry/registry-kubernetes/src/test/resources/log4j.xml
  registry/registry-kubernetes/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  registry/registry-kubernetes/src/test/resources/sofa-rpc/rpc-config.json
Labels: cla:yes, size/XL

#1397 fix lost interface name and method name in tracer when no such method…
  bootstrap/bootstrap-api/src/main/java/com/alipay/sofa/rpc/bootstrap/DefaultClientProxyInvoker.java
  tracer/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/filter/sofatracer/ProviderTracerFilter.java
  tracer/tracer-opentracing/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/RpcSofaTracer.java
  tracer/tracer-opentracing/src/test/java/com/alipay/sofa/rpc/event/SofaTracerSubscriberTest.java
Labels: bug, question, cla:yes, size/L

#1407 fix test case error
  test/test-integration/src/test/java/com/alipay/sofa/rpc/tracer/sofatracer/SofaTracerSubscriberTest.java
  test/test-integration/src/test/resources/sofa-rpc/rpc-config.json
Labels: bug, cla:yes, size/S

#1406 Enhanced for Nacos weight configuration
  registry/registry-nacos/src/main/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistryHelper.java
  registry/registry-nacos/src/test/java/com/alipay/sofa/rpc/registry/nacos/NacosRegistryHelperTest.java
Labels: cla:yes, size/M
