Repository sofastack/sofa-rpc, pull requests merged in 2025-03, with the labels that each got.

#1478 fix method timeout resolve problem
  core/api/src/main/java/com/alipay/sofa/rpc/config/ConsumerConfig.java
  core/api/src/test/java/com/alipay/sofa/rpc/config/ConsumerConfigTest.java
Labels: bug, cla:yes, size/M

#1480 fix triple stream deserialize issue when in serverless scene
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/message/triple/stream/ClientStreamObserverAdapter.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/transport/triple/TripleClientInvoker.java
Labels: bug, question, cla:yes, size/M

#1482 fix: hessian deserialize support sofa.serialize.dynamic.load.enable
  codec/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SingleClassLoaderSofaSerializerFactory.java
  codec/codec-sofa-hessian/src/test/java/com/alipay/sofa/rpc/codec/sofahessian/SingleClassLoaderSofaSerializerFactoryTest.java
Labels: bug, cla:yes, size/M

#1483 fix too many ping problem
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/TripleServer.java
Labels: bug, cla:yes, size/XS

#1484 Fix serialization and deserialization classloader issues in serverless scene
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/message/triple/stream/ClientStreamObserverAdapter.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/server/triple/GenericServiceImpl.java
Labels: bug, cla:yes, size/M

#1485 5.13.3 release
  all/pom.xml
  bom/pom.xml
  core/api/src/main/java/com/alipay/sofa/rpc/common/Version.java
  pom.xml
Labels: cla:yes, size/XS

#1463 fix: hessian deserialize support sofa.serialize.dynamic.load.enable
  codec/codec-sofa-hessian/src/main/java/com/alipay/sofa/rpc/codec/sofahessian/SingleClassLoaderSofaSerializerFactory.java
  codec/codec-sofa-hessian/src/test/java/com/alipay/sofa/rpc/codec/sofahessian/SingleClassLoaderSofaSerializerFactoryTest.java
Labels: bug, cla:yes, First-time contributor, size/M

#1467 fix the triple header context transfer issue
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/interceptor/ServerReqHeaderInterceptor.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/TracingContextKey.java
  remoting/remoting-triple/src/main/java/com/alipay/sofa/rpc/tracer/sofatracer/TripleTracerAdapter.java
  remoting/remoting-triple/src/test/java/com/alipay/sofa/rpc/tracer/sofatracer/TripleTracerAdapterTest.java
Labels: bug, cla:yes, size/M
